// 알파벳 데이터와 각 알파벳으로 시작하는 단어들
export interface Word {
  word: string; // 영어 단어
  korean: string; // 한국어 뜻
  emoji: string; // 시각적 표시용 이모지
}

export interface AlphabetData {
  uppercase: string; // 대문자
  lowercase: string; // 소문자
  name: string; // 알파벳 이름 (예: "에이")
  words: Word[]; // 해당 알파벳으로 시작하는 단어들
}

export const alphabetData: AlphabetData[] = [
  {
    uppercase: 'A',
    lowercase: 'a',
    name: '에이',
    words: [
      { word: 'Apple', korean: '사과', emoji: '🍎' },
      { word: 'Ant', korean: '개미', emoji: '🐜' },
      { word: 'Arm', korean: '팔', emoji: '💪' },
      { word: 'Alligator', korean: '악어', emoji: '🐊' },
      { word: 'Airplane', korean: '비행기', emoji: '✈️' },
      { word: 'Arrow', korean: '화살', emoji: '➡️' },
      { word: 'Art', korean: '미술', emoji: '🎨' },
      { word: 'Ask', korean: '물어보다', emoji: '❓' },
      { word: 'Ape', korean: '유인원', emoji: '🦍' },
      { word: 'Arrow', korean: '화살표', emoji: '🏹' },
      { word: 'Ambulance', korean: '구급차', emoji: '🚑' },
      { word: 'Angel', korean: '천사', emoji: '👼' },
      { word: 'Animal', korean: '동물', emoji: '🐾' },
      { word: 'Acorn', korean: '도토리', emoji: '🌰' },
      { word: 'Astronaut', korean: '우주비행사', emoji: '👨‍🚀' },
      { word: 'At', korean: '~에', emoji: '📍' },
      { word: 'Aunt', korean: '이모', emoji: '👩' },
      { word: 'Autumn', korean: '가을', emoji: '🍂' },
      { word: 'Axe', korean: '도끼', emoji: '🪓' },
      { word: 'Add', korean: '더하기', emoji: '➕' },
      { word: 'After', korean: '이후', emoji: '⏰' },
      { word: 'Age', korean: '나이', emoji: '🎂' },
      { word: 'Ago', korean: '전에', emoji: '⏪' },
      { word: 'Aid', korean: '도움', emoji: '🆘' },
      { word: 'Aim', korean: '목표', emoji: '🎯' },
      { word: 'Air', korean: '공기', emoji: '💨' },
      { word: 'Alarm', korean: '알람', emoji: '⏰' },
    ],
  },
  {
    uppercase: 'B',
    lowercase: 'b',
    name: '비',
    words: [
      { word: 'Ball', korean: '공', emoji: '⚽' },
      { word: 'Bird', korean: '새', emoji: '🐦' },
      { word: 'Bear', korean: '곰', emoji: '🐻' },
      { word: 'Book', korean: '책', emoji: '📚' },
      { word: 'Banana', korean: '바나나', emoji: '🍌' },
      { word: 'Bus', korean: '버스', emoji: '🚌' },
      { word: 'Baby', korean: '아기', emoji: '👶' },
      { word: 'Boy', korean: '소년', emoji: '👦' },
      { word: 'Bed', korean: '침대', emoji: '🛏️' },
      { word: 'Box', korean: '상자', emoji: '📦' },
      { word: 'Bike', korean: '자전거', emoji: '🚲' },
      { word: 'Bee', korean: '벌', emoji: '🐝' },
      { word: 'Blue', korean: '파란색', emoji: '🔵' },
      { word: 'Bread', korean: '빵', emoji: '🍞' },
      { word: 'Butterfly', korean: '나비', emoji: '🦋' },
      { word: 'Boat', korean: '보트', emoji: '⛵' },
      { word: 'Bell', korean: '종', emoji: '🔔' },
      { word: 'Bat', korean: '박쥐', emoji: '🦇' },
      { word: 'Big', korean: '큰', emoji: '🔴' },
      { word: 'Bag', korean: '가방', emoji: '👜' },
      { word: 'Button', korean: '단추', emoji: '🔘' },
      { word: 'Bad', korean: '나쁜', emoji: '❌' },
      { word: 'Back', korean: '뒤', emoji: '🔙' },
      { word: 'Be', korean: '~이다', emoji: '✅' },
      { word: 'Bean', korean: '콩', emoji: '🫘' },
      { word: 'Beard', korean: '수염', emoji: '🧔' },
      { word: 'Beat', korean: '치다', emoji: '🥁' },
      { word: 'Beautiful', korean: '아름다운', emoji: '✨' },
      { word: 'Bedroom', korean: '침실', emoji: '🛏️' },
      { word: 'Beep', korean: '삐삐', emoji: '📢' },
    ],
  },
  {
    uppercase: 'C',
    lowercase: 'c',
    name: '씨',
    words: [
      { word: 'Cat', korean: '고양이', emoji: '🐱' },
      { word: 'Car', korean: '자동차', emoji: '🚗' },
      { word: 'Cake', korean: '케이크', emoji: '🎂' },
      { word: 'Cow', korean: '소', emoji: '🐄' },
      { word: 'Cloud', korean: '구름', emoji: '☁️' },
      { word: 'Cup', korean: '컵', emoji: '☕' },
      { word: 'Candy', korean: '사탕', emoji: '🍬' },
      { word: 'Cap', korean: '모자', emoji: '🧢' },
      { word: 'Crayon', korean: '크레용', emoji: '🖍️' },
      { word: 'Chicken', korean: '닭', emoji: '🐔' },
      { word: 'Chair', korean: '의자', emoji: '💺' },
      { word: 'Circle', korean: '원', emoji: '⭕' },
      { word: 'Color', korean: '색깔', emoji: '🌈' },
      { word: 'Cookie', korean: '쿠키', emoji: '🍪' },
      { word: 'Corn', korean: '옥수수', emoji: '🌽' },
      { word: 'Cut', korean: '자르다', emoji: '✂️' },
      { word: 'Can', korean: '~할 수 있다', emoji: '✅' },
      { word: 'Come', korean: '오다', emoji: '➡️' },
      { word: 'Call', korean: '부르다', emoji: '📞' },
      { word: 'Camel', korean: '낙타', emoji: '🐪' },
      { word: 'Camp', korean: '캠프', emoji: '⛺' },
      { word: 'Can', korean: '캔', emoji: '🥫' },
      { word: 'Candle', korean: '양초', emoji: '🕯️' },
      { word: 'Cannon', korean: '대포', emoji: '💣' },
      { word: 'Card', korean: '카드', emoji: '🃏' },
      { word: 'Care', korean: '돌봄', emoji: '💕' },
      { word: 'Carpet', korean: '카펫', emoji: '🟨' },
      { word: 'Carrot', korean: '당근', emoji: '🥕' },
      { word: 'Castle', korean: '성', emoji: '🏰' },
      { word: 'Catch', korean: '잡다', emoji: '🤲' },
    ],
  },
  {
    uppercase: 'D',
    lowercase: 'd',
    name: '디',
    words: [
      { word: 'Dog', korean: '강아지', emoji: '🐶' },
      { word: 'Duck', korean: '오리', emoji: '🦆' },
      { word: 'Dinosaur', korean: '공룡', emoji: '🦕' },
      { word: 'Door', korean: '문', emoji: '🚪' },
      { word: 'Doll', korean: '인형', emoji: '🎎' },
      { word: 'Dad', korean: '아빠', emoji: '👨' },
      { word: 'Day', korean: '하루', emoji: '☀️' },
      { word: 'Desk', korean: '책상', emoji: '🪑' },
      { word: 'Dance', korean: '춤', emoji: '💃' },
      { word: 'Draw', korean: '그리다', emoji: '✏️' },
      { word: 'Drum', korean: '드럼', emoji: '🥁' },
      { word: 'Diamond', korean: '다이아몬드', emoji: '💎' },
      { word: 'Dig', korean: '파다', emoji: '⛏️' },
      { word: 'Dark', korean: '어두운', emoji: '🌑' },
      { word: 'Date', korean: '날짜', emoji: '📅' },
      { word: 'Deep', korean: '깊은', emoji: '🌊' },
      { word: 'Deer', korean: '사슴', emoji: '🦌' },
      { word: 'Dentist', korean: '치과의사', emoji: '🦷' },
      { word: 'Did', korean: '했다', emoji: '✅' },
      { word: 'Die', korean: '주사위', emoji: '🎲' },
      { word: 'Dirty', korean: '더러운', emoji: '🪣' },
      { word: 'Dish', korean: '접시', emoji: '🍽️' },
      { word: 'Do', korean: '하다', emoji: '✅' },
      { word: 'Doctor', korean: '의사', emoji: '👨‍⚕️' },
      { word: 'Dolphin', korean: '돌고래', emoji: '🐬' },
      { word: 'Donkey', korean: '당나귀', emoji: '🫏' },
      { word: 'Down', korean: '아래로', emoji: '⬇️' },
      { word: 'Dream', korean: '꿈', emoji: '💭' },
      { word: 'Dress', korean: '드레스', emoji: '👗' },
      { word: 'Drink', korean: '마시다', emoji: '🥤' },
    ],
  },
  {
    uppercase: 'E',
    lowercase: 'e',
    name: '이',
    words: [
      { word: 'Elephant', korean: '코끼리', emoji: '🐘' },
      { word: 'Egg', korean: '달걀', emoji: '🥚' },
      { word: 'Eagle', korean: '독수리', emoji: '🦅' },
      { word: 'Eye', korean: '눈', emoji: '👁️' },
      { word: 'Earth', korean: '지구', emoji: '🌍' },
      { word: 'Ear', korean: '귀', emoji: '👂' },
      { word: 'Eat', korean: '먹다', emoji: '🍽️' },
      { word: 'Eight', korean: '8', emoji: '8️⃣' },
      { word: 'Elbow', korean: '팔꿈치', emoji: '🦵' },
      { word: 'Elf', korean: '요정', emoji: '🧝' },
      { word: 'Empty', korean: '빈', emoji: '📭' },
      { word: 'End', korean: '끝', emoji: '🔚' },
      { word: 'Engine', korean: '엔진', emoji: '⚙️' },
      { word: 'Envelope', korean: '봉투', emoji: '✉️' },
      { word: 'Equal', korean: '같은', emoji: '⚖️' },
      { word: 'Eraser', korean: '지우개', emoji: '🧽' },
      { word: 'Even', korean: '짝수', emoji: '2️⃣' },
      { word: 'Every', korean: '모든', emoji: '🔄' },
      { word: 'Exit', korean: '나가다', emoji: '🚪' },
      { word: 'Extra', korean: '추가', emoji: '➕' },
      { word: 'Eyes', korean: '눈들', emoji: '👀' },
      { word: 'Earring', korean: '귀걸이', emoji: '💎' },
      { word: 'Early', korean: '일찍', emoji: '🌅' },
      { word: 'Easy', korean: '쉬운', emoji: '👍' },
      { word: 'Echo', korean: '메아리', emoji: '🔊' },
      { word: 'Edge', korean: '가장자리', emoji: '📐' },
      { word: 'Eel', korean: '뱀장어', emoji: '🐍' },
    ],
  },
  {
    uppercase: 'F',
    lowercase: 'f',
    name: '에프',
    words: [
      { word: 'Fish', korean: '물고기', emoji: '🐠' },
      { word: 'Flower', korean: '꽃', emoji: '🌸' },
      { word: 'Frog', korean: '개구리', emoji: '🐸' },
      { word: 'Fire', korean: '불', emoji: '🔥' },
      { word: 'Fox', korean: '여우', emoji: '🦊' },
      { word: 'Face', korean: '얼굴', emoji: '😊' },
      { word: 'Fan', korean: '부채', emoji: '🌀' },
      { word: 'Farm', korean: '농장', emoji: '🚜' },
      { word: 'Fast', korean: '빠른', emoji: '⚡' },
      { word: 'Father', korean: '아버지', emoji: '👨' },
      { word: 'Feather', korean: '깃털', emoji: '🪶' },
      { word: 'Feed', korean: '먹이다', emoji: '🍼' },
      { word: 'Feel', korean: '느끼다', emoji: '🤲' },
      { word: 'Feet', korean: '발들', emoji: '🦶' },
      { word: 'Fence', korean: '울타리', emoji: '🚧' },
      { word: 'Few', korean: '조금', emoji: '👋' },
      { word: 'Field', korean: '들판', emoji: '🌾' },
      { word: 'Fight', korean: '싸우다', emoji: '⚔️' },
      { word: 'Find', korean: '찾다', emoji: '🔍' },
      { word: 'Fine', korean: '좋은', emoji: '👍' },
      { word: 'Finger', korean: '손가락', emoji: '👆' },
      { word: 'Finish', korean: '끝내다', emoji: '🏁' },
      { word: 'First', korean: '첫번째', emoji: '1️⃣' },
      { word: 'Five', korean: '5', emoji: '5️⃣' },
      { word: 'Fix', korean: '고치다', emoji: '🔧' },
      { word: 'Flag', korean: '깃발', emoji: '🚩' },
      { word: 'Flat', korean: '평평한', emoji: '📏' },
      { word: 'Floor', korean: '바닥', emoji: '⬜' },
      { word: 'Fly', korean: '날다', emoji: '✈️' },
      { word: 'Food', korean: '음식', emoji: '🍎' },
    ],
  },
  {
    uppercase: 'G',
    lowercase: 'g',
    name: '지',
    words: [
      { word: 'Giraffe', korean: '기린', emoji: '🦒' },
      { word: 'Gift', korean: '선물', emoji: '🎁' },
      { word: 'Guitar', korean: '기타', emoji: '🎸' },
      { word: 'Grass', korean: '잔디', emoji: '🌱' },
      { word: 'Girl', korean: '소녀', emoji: '👧' },
      { word: 'Game', korean: '게임', emoji: '🎮' },
      { word: 'Garden', korean: '정원', emoji: '🌻' },
      { word: 'Gas', korean: '가스', emoji: '⛽' },
      { word: 'Gate', korean: '문', emoji: '🚧' },
      { word: 'Get', korean: '얻다', emoji: '🤲' },
      { word: 'Ghost', korean: '유령', emoji: '👻' },
      { word: 'Giant', korean: '거인', emoji: '👹' },
      { word: 'Give', korean: '주다', emoji: '🤝' },
      { word: 'Glad', korean: '기쁜', emoji: '😊' },
      { word: 'Glass', korean: '유리', emoji: '🥛' },
      { word: 'Glove', korean: '장갑', emoji: '🧤' },
      { word: 'Go', korean: '가다', emoji: '🚶' },
      { word: 'Goat', korean: '염소', emoji: '🐐' },
      { word: 'God', korean: '신', emoji: '✨' },
      { word: 'Gold', korean: '금', emoji: '🥇' },
      { word: 'Good', korean: '좋은', emoji: '👍' },
      { word: 'Goose', korean: '거위', emoji: '🪿' },
      { word: 'Grape', korean: '포도', emoji: '🍇' },
      { word: 'Gray', korean: '회색', emoji: '⚪' },
      { word: 'Great', korean: '훌륭한', emoji: '🌟' },
      { word: 'Green', korean: '초록색', emoji: '🟢' },
      { word: 'Grow', korean: '자라다', emoji: '📈' },
      { word: 'Gum', korean: '껌', emoji: '🍬' },
      { word: 'Gun', korean: '총', emoji: '🔫' },
      { word: 'Guy', korean: '사람', emoji: '👤' },
    ],
  },
  {
    uppercase: 'H',
    lowercase: 'h',
    name: '에이치',
    words: [
      { word: 'House', korean: '집', emoji: '🏠' },
      { word: 'Heart', korean: '하트', emoji: '❤️' },
      { word: 'Horse', korean: '말', emoji: '🐴' },
      { word: 'Hat', korean: '모자', emoji: '🎩' },
      { word: 'Hand', korean: '손', emoji: '✋' },
      { word: 'Head', korean: '머리', emoji: '👤' },
      { word: 'Hello', korean: '안녕', emoji: '👋' },
      { word: 'Help', korean: '도움', emoji: '🆘' },
      { word: 'Hen', korean: '암탉', emoji: '🐔' },
      { word: 'Here', korean: '여기', emoji: '📍' },
      { word: 'Hide', korean: '숨다', emoji: '🙈' },
      { word: 'High', korean: '높은', emoji: '⛰️' },
      { word: 'Hill', korean: '언덕', emoji: '🌄' },
      { word: 'Hip', korean: '엉덩이', emoji: '🦵' },
      { word: 'Hit', korean: '치다', emoji: '👊' },
      { word: 'Hive', korean: '벌집', emoji: '🍯' },
      { word: 'Hole', korean: '구멍', emoji: '🕳️' },
      { word: 'Home', korean: '집', emoji: '🏡' },
      { word: 'Hop', korean: '뛰다', emoji: '🐰' },
      { word: 'Horn', korean: '뿔', emoji: '📯' },
      { word: 'Hot', korean: '뜨거운', emoji: '🔥' },
      { word: 'Hour', korean: '시간', emoji: '🕐' },
      { word: 'How', korean: '어떻게', emoji: '❓' },
      { word: 'Hug', korean: '안아주다', emoji: '🤗' },
      { word: 'Huge', korean: '거대한', emoji: '🌍' },
      { word: 'Hum', korean: '흥얼거리다', emoji: '🎵' },
      { word: 'Hunt', korean: '사냥하다', emoji: '🎯' },
      { word: 'Hurt', korean: '아프다', emoji: '😢' },
      { word: 'Hut', korean: '오두막', emoji: '🛖' },
      { word: 'Hymn', korean: '찬송가', emoji: '📜' },
    ],
  },
  {
    uppercase: 'I',
    lowercase: 'i',
    name: '아이',
    words: [
      { word: 'Ice', korean: '얼음', emoji: '🧊' },
      { word: 'Ice cream', korean: '아이스크림', emoji: '🍦' },
      { word: 'Igloo', korean: '이글루', emoji: '🏠' },
      { word: 'Island', korean: '섬', emoji: '🏝️' },
      { word: 'Insect', korean: '곤충', emoji: '🐛' },
      { word: 'I', korean: '나', emoji: '👤' },
      { word: 'Ice', korean: '얼음', emoji: '❄️' },
      { word: 'Idea', korean: '아이디어', emoji: '💡' },
      { word: 'If', korean: '만약', emoji: '🤔' },
      { word: 'Ill', korean: '아픈', emoji: '🤒' },
      { word: 'In', korean: '안에', emoji: '📥' },
      { word: 'Ink', korean: '잉크', emoji: '🖋️' },
      { word: 'Into', korean: '안으로', emoji: '➡️' },
      { word: 'Iron', korean: '다리미', emoji: '⚙️' },
      { word: 'Is', korean: '~이다', emoji: '✅' },
      { word: 'It', korean: '그것', emoji: '👉' },
      { word: 'Its', korean: '그의', emoji: '👈' },
      { word: 'Item', korean: '항목', emoji: '📋' },
      { word: 'Idol', korean: '우상', emoji: '⭐' },
      { word: 'Ideal', korean: '이상적인', emoji: '✨' },
      { word: 'Idle', korean: '한가한', emoji: '😴' },
      { word: 'Idol', korean: '아이돌', emoji: '🎤' },
      { word: 'Image', korean: '이미지', emoji: '🖼️' },
      { word: 'Inch', korean: '인치', emoji: '📏' },
      { word: 'Inside', korean: '안쪽', emoji: '📦' },
      { word: 'Instant', korean: '즉시', emoji: '⚡' },
      { word: 'Instead', korean: '대신에', emoji: '🔄' },
    ],
  },
  {
    uppercase: 'J',
    lowercase: 'j',
    name: '제이',
    words: [
      { word: 'Jellyfish', korean: '해파리', emoji: '🎐' },
      { word: 'Juice', korean: '주스', emoji: '🧃' },
      { word: 'Jacket', korean: '재킷', emoji: '🧥' },
      { word: 'Jelly', korean: '젤리', emoji: '🍮' },
      { word: 'Jump', korean: '뛰기', emoji: '🦘' },
      { word: 'Jar', korean: '항아리', emoji: '🫙' },
      { word: 'Jaw', korean: '턱', emoji: '😬' },
      { word: 'Jet', korean: '제트기', emoji: '✈️' },
      { word: 'Jewel', korean: '보석', emoji: '💎' },
      { word: 'Jig', korean: '지그', emoji: '🕺' },
      { word: 'Jiggle', korean: '흔들리다', emoji: '🔄' },
      { word: 'Jingle', korean: '딸랑딸랑', emoji: '🔔' },
      { word: 'Job', korean: '일', emoji: '💼' },
      { word: 'Jog', korean: '조깅하다', emoji: '🏃' },
      { word: 'Join', korean: '참여하다', emoji: '🤝' },
      { word: 'Joke', korean: '농담', emoji: '😄' },
      { word: 'Jolly', korean: '즐거운', emoji: '😊' },
      { word: 'Jot', korean: '빠르게 쓰다', emoji: '✏️' },
      { word: 'Joy', korean: '기쁨', emoji: '😃' },
      { word: 'Judge', korean: '판단하다', emoji: '⚖️' },
      { word: 'Jug', korean: '주전자', emoji: '🫖' },
      { word: 'Juggle', korean: '저글링하다', emoji: '🎪' },
      { word: 'Jugular', korean: '목정맥', emoji: '🩸' },
      { word: 'Juice', korean: '주스', emoji: '🧃' },
      { word: 'July', korean: '7월', emoji: '🌞' },
      { word: 'Jumbo', korean: '거대한', emoji: '🐘' },
      { word: 'Jump', korean: '뛰다', emoji: '🦘' },
      { word: 'June', korean: '6월', emoji: '🌼' },
      { word: 'Jungle', korean: '정글', emoji: '🌴' },
      { word: 'Junior', korean: '주니어', emoji: '👶' },
    ],
  },
  {
    uppercase: 'K',
    lowercase: 'k',
    name: '케이',
    words: [
      { word: 'Kangaroo', korean: '캥거루', emoji: '🦘' },
      { word: 'Key', korean: '열쇠', emoji: '🔑' },
      { word: 'King', korean: '왕', emoji: '👑' },
      { word: 'Kite', korean: '연', emoji: '🪁' },
      { word: 'Koala', korean: '코알라', emoji: '🐨' },
      { word: 'Kit', korean: '키트', emoji: '🧰' },
      { word: 'Kitchen', korean: '부엌', emoji: '🍳' },
      { word: 'Knee', korean: '무릎', emoji: '🦵' },
      { word: 'Kick', korean: '차다', emoji: '⚽' },
      { word: 'Kid', korean: '아이', emoji: '👶' },
      { word: 'Kind', korean: '친절한', emoji: '😊' },
      { word: 'Kiss', korean: '키스', emoji: '💋' },
      { word: 'Kite', korean: '연', emoji: '🪁' },
      { word: 'Kitten', korean: '고양이 새끼', emoji: '🐱' },
      { word: 'Kitchen', korean: '부엌', emoji: '🍳' },
      { word: 'Knee', korean: '무릎', emoji: '🦵' },
      { word: 'Knob', korean: '손잡이', emoji: '🚪' },
      { word: 'Knot', korean: '매듭', emoji: '🎀' },
      { word: 'Know', korean: '알다', emoji: '🧠' },
      { word: 'Keep', korean: '유지하다', emoji: '🤲' },
      { word: 'Keen', korean: '예리한', emoji: '👀' },
      { word: 'Kelp', korean: '다시마', emoji: '🌿' },
      { word: 'Kettle', korean: '주전자', emoji: '🫖' },
      { word: 'Kick', korean: '차다', emoji: '⚽' },
      { word: 'Kilt', korean: '킬트', emoji: '👗' },
      { word: 'Kin', korean: '친척', emoji: '👨‍👩‍👧‍👦' },
      { word: 'King', korean: '왕', emoji: '👑' },
      { word: 'Kiosk', korean: '키오스크', emoji: '🏪' },
      { word: 'Kit', korean: '키트', emoji: '🧰' },
    ],
  },
  {
    uppercase: 'L',
    lowercase: 'l',
    name: '엘',
    words: [
      { word: 'Lion', korean: '사자', emoji: '🦁' },
      { word: 'Leaf', korean: '나뭇잎', emoji: '🍃' },
      { word: 'Lamp', korean: '램프', emoji: '💡' },
      { word: 'Lollipop', korean: '막대사탕', emoji: '🍭' },
      { word: 'Lemon', korean: '레몬', emoji: '🍋' },
      { word: 'Like', korean: '좋아하다', emoji: '❤️' },
      { word: 'Love', korean: '사랑', emoji: '💕' },
      { word: 'Look', korean: '보다', emoji: '👀' },
      { word: 'Long', korean: '긴', emoji: '📏' },
      { word: 'Loud', korean: '시끄러운', emoji: '🔊' },
      { word: 'Lady', korean: '여자', emoji: '👩' },
      { word: 'Lake', korean: '호수', emoji: '🏞️' },
      { word: 'Lamb', korean: '양', emoji: '🐑' },
      { word: 'Lane', korean: '차선', emoji: '🛣️' },
      { word: 'Last', korean: '마지막', emoji: '🔚' },
      { word: 'Late', korean: '늦은', emoji: '⏰' },
      { word: 'Laugh', korean: '웃다', emoji: '😄' },
      { word: 'Law', korean: '법', emoji: '⚖️' },
      { word: 'Lay', korean: '누이다', emoji: '🛏️' },
      { word: 'Lazy', korean: '게으른', emoji: '😴' },
      { word: 'Lead', korean: '이끌다', emoji: '👤' },
      { word: 'Learn', korean: '배우다', emoji: '📚' },
      { word: 'Left', korean: '왼쪽', emoji: '⬅️' },
      { word: 'Leg', korean: '다리', emoji: '🦵' },
      { word: 'Let', korean: '허락하다', emoji: '✅' },
      { word: 'Letter', korean: '편지', emoji: '✉️' },
      { word: 'Lick', korean: '핥다', emoji: '👅' },
      { word: 'Lid', korean: '뚜껑', emoji: '🪣' },
      { word: 'Lie', korean: '거짓말', emoji: '🤥' },
      { word: 'Life', korean: '생명', emoji: '🌟' },
    ],
  },
  {
    uppercase: 'M',
    lowercase: 'm',
    name: '엠',
    words: [
      { word: 'Moon', korean: '달', emoji: '🌙' },
      { word: 'Monkey', korean: '원숭이', emoji: '🐵' },
      { word: 'Mouse', korean: '쥐', emoji: '🐭' },
      { word: 'Milk', korean: '우유', emoji: '🥛' },
      { word: 'Music', korean: '음악', emoji: '🎵' },
      { word: 'Mom', korean: '엄마', emoji: '👩' },
      { word: 'Map', korean: '지도', emoji: '🗺️' },
      { word: 'Man', korean: '남자', emoji: '👨' },
      { word: 'Mat', korean: '매트', emoji: '🏃' },
      { word: 'May', korean: '5월', emoji: '🌸' },
      { word: 'Me', korean: '나를', emoji: '👤' },
      { word: 'Meat', korean: '고기', emoji: '🥩' },
      { word: 'Meet', korean: '만나다', emoji: '🤝' },
      { word: 'Melt', korean: '녹다', emoji: '🫠' },
      { word: 'Men', korean: '남자들', emoji: '👨‍👨' },
      { word: 'Mess', korean: '엉망', emoji: '📦' },
      { word: 'Mid', korean: '중간', emoji: '📍' },
      { word: 'Mix', korean: '섞다', emoji: '🔄' },
      { word: 'Mode', korean: '모드', emoji: '⚙️' },
      { word: 'Mom', korean: '엄마', emoji: '👩' },
      { word: 'Mop', korean: '대걸레', emoji: '🧹' },
      { word: 'More', korean: '더', emoji: '➕' },
      { word: 'Most', korean: '대부분', emoji: '🔝' },
      { word: 'Move', korean: '움직이다', emoji: '🚶' },
      { word: 'Much', korean: '많은', emoji: '📊' },
      { word: 'Mud', korean: '진흙', emoji: '🟤' },
      { word: 'Mug', korean: '머그컵', emoji: '☕' },
      { word: 'Mule', korean: '노새', emoji: '🫏' },
      { word: 'Must', korean: '해야 한다', emoji: '✅' },
      { word: 'My', korean: '내', emoji: '👤' },
    ],
  },
  {
    uppercase: 'N',
    lowercase: 'n',
    name: '엔',
    words: [
      { word: 'Nest', korean: '둥지', emoji: '🪺' },
      { word: 'Nose', korean: '코', emoji: '👃' },
      { word: 'Net', korean: '그물', emoji: '🕸️' },
      { word: 'Night', korean: '밤', emoji: '🌃' },
      { word: 'Nurse', korean: '간호사', emoji: '👩‍⚕️' },
      { word: 'No', korean: '아니오', emoji: '❌' },
      { word: 'Not', korean: '아니다', emoji: '🚫' },
      { word: 'Now', korean: '지금', emoji: '⏰' },
      { word: 'New', korean: '새로운', emoji: '🆕' },
      { word: 'Nice', korean: '좋은', emoji: '👍' },
      { word: 'Name', korean: '이름', emoji: '🏷️' },
      { word: 'Nap', korean: '낮잠', emoji: '😴' },
      { word: 'Nail', korean: '손톱', emoji: '💅' },
      { word: 'Near', korean: '가까운', emoji: '📍' },
      { word: 'Neat', korean: '깔끔한', emoji: '✨' },
      { word: 'Neck', korean: '목', emoji: '👔' },
      { word: 'Need', korean: '필요하다', emoji: '❗' },
      { word: 'Neon', korean: '네온', emoji: '💡' },
      { word: 'Nephew', korean: '조카', emoji: '👶' },
      { word: 'Next', korean: '다음', emoji: '➡️' },
      { word: 'Nibble', korean: '조금씩 먹다', emoji: '🍪' },
      { word: 'Nice', korean: '멋진', emoji: '😊' },
      { word: 'Nick', korean: '작은 상처', emoji: '🩹' },
      { word: 'Niece', korean: '조카딸', emoji: '👧' },
      { word: 'Nine', korean: '9', emoji: '9️⃣' },
      { word: 'Nip', korean: '꼬집다', emoji: '🤏' },
      { word: 'Nod', korean: '고개를 끄덕이다', emoji: '👍' },
      { word: 'None', korean: '아무것도', emoji: '🚫' },
      { word: 'Nook', korean: '구석', emoji: '📚' },
      { word: 'Noon', korean: '정오', emoji: '☀️' },
    ],
  },
  {
    uppercase: 'O',
    lowercase: 'o',
    name: '오',
    words: [
      { word: 'Octopus', korean: '문어', emoji: '🐙' },
      { word: 'Orange', korean: '오렌지', emoji: '🍊' },
      { word: 'Owl', korean: '올빼미', emoji: '🦉' },
      { word: 'Ocean', korean: '바다', emoji: '🌊' },
      { word: 'Onion', korean: '양파', emoji: '🧅' },
      { word: 'Of', korean: '~의', emoji: '👈' },
      { word: 'Off', korean: '꺼진', emoji: '🔴' },
      { word: 'Oh', korean: '오', emoji: '😲' },
      { word: 'Oil', korean: '기름', emoji: '🛢️' },
      { word: 'Ok', korean: '좋아', emoji: '👍' },
      { word: 'Old', korean: '오래된', emoji: '👴' },
      { word: 'On', korean: '위에', emoji: '⬆️' },
      { word: 'Once', korean: '한 번', emoji: '1️⃣' },
      { word: 'One', korean: '하나', emoji: '1️⃣' },
      { word: 'Only', korean: '오직', emoji: '👆' },
      { word: 'Onto', korean: '위로', emoji: '⬆️' },
      { word: 'Open', korean: '열다', emoji: '📖' },
      { word: 'Or', korean: '또는', emoji: '↔️' },
      { word: 'Order', korean: '순서', emoji: '🔢' },
      { word: 'Out', korean: '밖으로', emoji: '🚪' },
      { word: 'Oval', korean: '타원형', emoji: '🥚' },
      { word: 'Over', korean: '위에', emoji: '☁️' },
      { word: 'Owe', korean: '빚지다', emoji: '💰' },
      { word: 'Owl', korean: '올빼미', emoji: '🦉' },
      { word: 'Own', korean: '자신의', emoji: '👤' },
      { word: 'Ox', korean: '소', emoji: '🐂' },
      { word: 'Oat', korean: '귀리', emoji: '🌾' },
      { word: 'Oath', korean: '맹세', emoji: '✋' },
      { word: 'Oats', korean: '오트밀', emoji: '🥣' },
      { word: 'Oboe', korean: '오보에', emoji: '🎵' },
    ],
  },
  {
    uppercase: 'P',
    lowercase: 'p',
    name: '피',
    words: [
      { word: 'Pig', korean: '돼지', emoji: '🐷' },
      { word: 'Penguin', korean: '펭귄', emoji: '🐧' },
      { word: 'Pizza', korean: '피자', emoji: '🍕' },
      { word: 'Plant', korean: '식물', emoji: '🌿' },
      { word: 'Pencil', korean: '연필', emoji: '✏️' },
      { word: 'Play', korean: '놀다', emoji: '🎮' },
      { word: 'Park', korean: '공원', emoji: '🌳' },
      { word: 'Pen', korean: '펜', emoji: '✍️' },
      { word: 'Pan', korean: '팬', emoji: '🍳' },
      { word: 'Pat', korean: '토닥이다', emoji: '👋' },
      { word: 'Path', korean: '길', emoji: '🛤️' },
      { word: 'Pay', korean: '지불하다', emoji: '💰' },
      { word: 'Pea', korean: '완두콩', emoji: '🫛' },
      { word: 'Peak', korean: '정상', emoji: '⛰️' },
      { word: 'Peal', korean: '울림', emoji: '🔔' },
      { word: 'Pear', korean: '배', emoji: '🍐' },
      { word: 'Peck', korean: '쪼다', emoji: '🐦' },
      { word: 'Peel', korean: '껍질', emoji: '🍌' },
      { word: 'Peep', korean: '엿보다', emoji: '👁️' },
      { word: 'Peer', korean: '동료', emoji: '👥' },
      { word: 'Peg', korean: '못', emoji: '📌' },
      { word: 'Per', korean: '당', emoji: '📊' },
      { word: 'Pet', korean: '애완동물', emoji: '🐾' },
      { word: 'Pew', korean: '벤치', emoji: '💺' },
      { word: 'Pie', korean: '파이', emoji: '🥧' },
      { word: 'Pig', korean: '돼지', emoji: '🐷' },
      { word: 'Pin', korean: '핀', emoji: '📌' },
      { word: 'Pit', korean: '구덩이', emoji: '🕳️' },
      { word: 'Pod', korean: '꼬투리', emoji: '🫘' },
      { word: 'Pop', korean: '팝', emoji: '🎵' },
    ],
  },
  {
    uppercase: 'Q',
    lowercase: 'q',
    name: '큐',
    words: [
      { word: 'Queen', korean: '여왕', emoji: '👸' },
      { word: 'Quilt', korean: '이불', emoji: '🛏️' },
      { word: 'Quack', korean: '꽥꽥', emoji: '🦆' },
      { word: 'Question', korean: '질문', emoji: '❓' },
      { word: 'Quiet', korean: '조용한', emoji: '🤫' },
      { word: 'Quail', korean: '메추라기', emoji: '🐦' },
      { word: 'Quake', korean: '지진', emoji: '🌍' },
      { word: 'Qualify', korean: '자격을 얻다', emoji: '✅' },
      { word: 'Quality', korean: '품질', emoji: '⭐' },
      { word: 'Quantity', korean: '수량', emoji: '🔢' },
      { word: 'Quarrel', korean: '싸움', emoji: '😠' },
      { word: 'Quarry', korean: '채석장', emoji: '⛏️' },
      { word: 'Quarter', korean: '사분의 일', emoji: '¼' },
      { word: 'Quartet', korean: '4중주', emoji: '🎼' },
      { word: 'Quash', korean: '진압하다', emoji: '🛑' },
      { word: 'Quaver', korean: '떨리다', emoji: '🎵' },
      { word: 'Quay', korean: '부두', emoji: '⚓' },
      { word: 'Queasy', korean: '멀미나는', emoji: '🤢' },
      { word: 'Queer', korean: '이상한', emoji: '🤔' },
      { word: 'Quell', korean: '진압하다', emoji: '🛡️' },
      { word: 'Quench', korean: '끄다', emoji: '💧' },
      { word: 'Query', korean: '질문', emoji: '❓' },
      { word: 'Quest', korean: '탐험', emoji: '🗺️' },
      { word: 'Queue', korean: '줄', emoji: '👥' },
      { word: 'Quick', korean: '빠른', emoji: '⚡' },
      { word: 'Quid', korean: '궐련', emoji: '🚬' },
      { word: 'Quill', korean: '깃펜', emoji: '🪶' },
      { word: 'Quilt', korean: '누비이불', emoji: '🛏️' },
      { word: 'Quip', korean: '재치있는 말', emoji: '💬' },
      { word: 'Quire', korean: '한 묶음', emoji: '📄' },
    ],
  },
  {
    uppercase: 'R',
    lowercase: 'r',
    name: '알',
    words: [
      { word: 'Rabbit', korean: '토끼', emoji: '🐰' },
      { word: 'Rainbow', korean: '무지개', emoji: '🌈' },
      { word: 'Robot', korean: '로봇', emoji: '🤖' },
      { word: 'Rose', korean: '장미', emoji: '🌹' },
      { word: 'Rocket', korean: '로켓', emoji: '🚀' },
      { word: 'Red', korean: '빨간색', emoji: '🔴' },
      { word: 'Run', korean: '달리다', emoji: '🏃' },
      { word: 'Rat', korean: '쥐', emoji: '🐭' },
      { word: 'Ram', korean: '양', emoji: '🐏' },
      { word: 'Rap', korean: '탁 치다', emoji: '👋' },
      { word: 'Rap', korean: '랩', emoji: '🎤' },
      { word: 'Rare', korean: '드문', emoji: '💎' },
      { word: 'Rash', korean: '발진', emoji: '🔴' },
      { word: 'Rat', korean: '쥐', emoji: '🐭' },
      { word: 'Rave', korean: '광란', emoji: '🎉' },
      { word: 'Raw', korean: '날것의', emoji: '🥩' },
      { word: 'Ray', korean: '광선', emoji: '☀️' },
      { word: 'Raze', korean: '파괴하다', emoji: '💥' },
      { word: 'Razor', korean: '면도기', emoji: '🪒' },
      { word: 'Reach', korean: '도달하다', emoji: '🤲' },
      { word: 'Read', korean: '읽다', emoji: '📖' },
      { word: 'Real', korean: '진짜의', emoji: '✅' },
      { word: 'Rear', korean: '뒤', emoji: '🔙' },
      { word: 'Reel', korean: '릴', emoji: '🎣' },
      { word: 'Reef', korean: '암초', emoji: '🌊' },
      { word: 'Reek', korean: '악취', emoji: '👃' },
      { word: 'Reel', korean: '비틀거리다', emoji: '🌀' },
      { word: 'Ref', korean: '심판', emoji: '⚖️' },
      { word: 'Regal', korean: '왕의', emoji: '👑' },
      { word: 'Reign', korean: '통치', emoji: '👑' },
    ],
  },
  {
    uppercase: 'S',
    lowercase: 's',
    name: '에스',
    words: [
      { word: 'Star', korean: '별', emoji: '⭐' },
      { word: 'Sun', korean: '태양', emoji: '☀️' },
      { word: 'Snake', korean: '뱀', emoji: '🐍' },
      { word: 'Sheep', korean: '양', emoji: '🐑' },
      { word: 'Spoon', korean: '숟가락', emoji: '🥄' },
      { word: 'See', korean: '보다', emoji: '👀' },
      { word: 'Say', korean: '말하다', emoji: '💬' },
      { word: 'Sit', korean: '앉다', emoji: '🪑' },
      { word: 'Stop', korean: '멈추다', emoji: '🛑' },
      { word: 'Stand', korean: '서다', emoji: '🚶' },
      { word: 'Sad', korean: '슬픈', emoji: '😢' },
      { word: 'Safe', korean: '안전한', emoji: '🛡️' },
      { word: 'Sage', korean: '현자', emoji: '🧙' },
      { word: 'Sail', korean: '항해하다', emoji: '⛵' },
      { word: 'Sale', korean: '판매', emoji: '💰' },
      { word: 'Salt', korean: '소금', emoji: '🧂' },
      { word: 'Same', korean: '같은', emoji: '🔄' },
      { word: 'Sand', korean: '모래', emoji: '🏖️' },
      { word: 'Sang', korean: '노래했다', emoji: '🎵' },
      { word: 'Sank', korean: '가라앉았다', emoji: '🌊' },
      { word: 'Sap', korean: '수액', emoji: '🌿' },
      { word: 'Sash', korean: '띠', emoji: '🎗️' },
      { word: 'Sat', korean: '앉았다', emoji: '🪑' },
      { word: 'Saw', korean: '보았다', emoji: '👁️' },
      { word: 'Saw', korean: '톱', emoji: '🪚' },
      { word: 'Sax', korean: '색소폰', emoji: '🎷' },
      { word: 'Say', korean: '말하다', emoji: '💬' },
      { word: 'Sea', korean: '바다', emoji: '🌊' },
      { word: 'Seal', korean: '물개', emoji: '🦭' },
      { word: 'Seam', korean: '봉합선', emoji: '🧵' },
    ],
  },
  {
    uppercase: 'T',
    lowercase: 't',
    name: '티',
    words: [
      { word: 'Tiger', korean: '호랑이', emoji: '🐯' },
      { word: 'Tree', korean: '나무', emoji: '🌳' },
      { word: 'Train', korean: '기차', emoji: '🚂' },
      { word: 'Toy', korean: '장난감', emoji: '🧸' },
      { word: 'Turtle', korean: '거북이', emoji: '🐢' },
      { word: 'The', korean: '그', emoji: '👈' },
      { word: 'To', korean: '~에게', emoji: '➡️' },
      { word: 'Too', korean: '또한', emoji: '➕' },
      { word: 'Two', korean: '2', emoji: '2️⃣' },
      { word: 'Tag', korean: '태그', emoji: '🏷️' },
      { word: 'Tan', korean: '황갈색', emoji: '🟤' },
      { word: 'Tap', korean: '두드리다', emoji: '👆' },
      { word: 'Tar', korean: '타르', emoji: '🛢️' },
      { word: 'Tat', korean: '싸구려', emoji: '💰' },
      { word: 'Tax', korean: '세금', emoji: '💸' },
      { word: 'Tea', korean: '차', emoji: '🫖' },
      { word: 'Ten', korean: '10', emoji: '🔟' },
      { word: 'The', korean: '그', emoji: '👈' },
      { word: 'Tie', korean: '넥타이', emoji: '👔' },
      { word: 'Tin', korean: '주석', emoji: '🥫' },
      { word: 'Tip', korean: '팁', emoji: '💡' },
      { word: 'Tit', korean: '동가리', emoji: '🐦' },
      { word: 'To', korean: '~에게', emoji: '➡️' },
      { word: 'Tod', korean: '여우', emoji: '🦊' },
      { word: 'Toe', korean: '발가락', emoji: '🦶' },
      { word: 'Tog', korean: '옷', emoji: '👕' },
      { word: 'Tom', korean: '수컷', emoji: '🐱' },
      { word: 'Ton', korean: '톤', emoji: '⚖️' },
      { word: 'Too', korean: '너무', emoji: '⚠️' },
      { word: 'Top', korean: '꼭대기', emoji: '🔝' },
      { word: 'Tor', korean: '바위산', emoji: '⛰️' },
    ],
  },
  {
    uppercase: 'U',
    lowercase: 'u',
    name: '유',
    words: [
      { word: 'Umbrella', korean: '우산', emoji: '☂️' },
      { word: 'Unicorn', korean: '유니콘', emoji: '🦄' },
      { word: 'Up', korean: '위', emoji: '⬆️' },
      { word: 'Under', korean: '아래', emoji: '⬇️' },
      { word: 'Us', korean: '우리', emoji: '👥' },
      { word: 'Use', korean: '사용하다', emoji: '🔧' },
      { word: 'Uber', korean: '우버', emoji: '🚗' },
      { word: 'Ugly', korean: '못생긴', emoji: '😞' },
      { word: 'Ulcer', korean: '궤양', emoji: '🩹' },
      { word: 'Ultra', korean: '초', emoji: '⚡' },
      { word: 'Umbra', korean: '그림자', emoji: '🌑' },
      { word: 'Uncle', korean: '삼촌', emoji: '👨' },
      { word: 'Undo', korean: '되돌리다', emoji: '↩️' },
      { word: 'Unfit', korean: '부적합한', emoji: '❌' },
      { word: 'Unify', korean: '통합하다', emoji: '🔗' },
      { word: 'Union', korean: '연합', emoji: '🤝' },
      { word: 'Unit', korean: '단위', emoji: '📦' },
      { word: 'Unity', korean: '통일', emoji: '🌍' },
      { word: 'Unleash', korean: '풀어놓다', emoji: '🔓' },
      { word: 'Until', korean: '~까지', emoji: '⏰' },
      { word: 'Untie', korean: '풀다', emoji: '🔓' },
      { word: 'Unto', korean: '~에게', emoji: '➡️' },
      { word: 'Untold', korean: '말로 못할', emoji: '🤐' },
      { word: 'Unused', korean: '사용하지 않은', emoji: '📦' },
      { word: 'Unveil', korean: '공개하다', emoji: '👁️' },
      { word: 'Unzip', korean: '지퍼를 열다', emoji: '🤐' },
      { word: 'Upon', korean: '~위에', emoji: '⬆️' },
      { word: 'Upper', korean: '위쪽', emoji: '☁️' },
      { word: 'Upset', korean: '화난', emoji: '😠' },
    ],
  },
  {
    uppercase: 'V',
    lowercase: 'v',
    name: '브이',
    words: [
      { word: 'Violin', korean: '바이올린', emoji: '🎻' },
      { word: 'Vase', korean: '꽃병', emoji: '🏺' },
      { word: 'Vase', korean: '꽃병', emoji: '🏺' },
      { word: 'Volcano', korean: '화산', emoji: '🌋' },
      { word: 'Van', korean: '밴', emoji: '🚐' },
      { word: 'Vac', korean: '진공청소기', emoji: '🧹' },
      { word: 'Vain', korean: '허영심 많은', emoji: '🪞' },
      { word: 'Vale', korean: '계곡', emoji: '🏔️' },
      { word: 'Valet', korean: '발렛', emoji: '🚗' },
      { word: 'Valley', korean: '계곡', emoji: '🏔️' },
      { word: 'Value', korean: '가치', emoji: '💎' },
      { word: 'Valve', korean: '밸브', emoji: '🔧' },
      { word: 'Vamp', korean: '밴드', emoji: '👠' },
      { word: 'Vane', korean: '날개', emoji: '🌀' },
      { word: 'Vang', korean: '밴', emoji: '⛵' },
      { word: 'Vary', korean: '변화하다', emoji: '🔄' },
      { word: 'Vase', korean: '화분', emoji: '🏺' },
      { word: 'Vast', korean: '넓은', emoji: '🌍' },
      { word: 'Vat', korean: '큰 통', emoji: '🪣' },
      { word: 'Vault', korean: '금고', emoji: '🏦' },
      { word: 'Veal', korean: '송아지 고기', emoji: '🥩' },
      { word: 'Veer', korean: '방향을 바꾸다', emoji: '🔄' },
      { word: 'Veil', korean: '베일', emoji: '👰' },
      { word: 'Vein', korean: '정맥', emoji: '🩸' },
      { word: 'Veld', korean: '사바나', emoji: '🌾' },
      { word: 'Vend', korean: '팔다', emoji: '💰' },
      { word: 'Venom', korean: '독', emoji: '☠️' },
      { word: 'Vent', korean: '환기구', emoji: '💨' },
      { word: 'Verb', korean: '동사', emoji: '📝' },
      { word: 'Verdict', korean: '판결', emoji: '⚖️' },
    ],
  },
  {
    uppercase: 'W',
    lowercase: 'w',
    name: '더블유',
    words: [
      { word: 'Water', korean: '물', emoji: '💧' },
      { word: 'Whale', korean: '고래', emoji: '🐋' },
      { word: 'Wind', korean: '바람', emoji: '💨' },
      { word: 'Window', korean: '창문', emoji: '🪟' },
      { word: 'Worm', korean: '벌레', emoji: '🐛' },
      { word: 'We', korean: '우리', emoji: '👥' },
      { word: 'Wag', korean: '흔들다', emoji: '🐕' },
      { word: 'Wage', korean: '임금', emoji: '💰' },
      { word: 'Wail', korean: '울부짖다', emoji: '😭' },
      { word: 'Wait', korean: '기다리다', emoji: '⏰' },
      { word: 'Wake', korean: '깨다', emoji: '😴' },
      { word: 'Walk', korean: '걷다', emoji: '🚶' },
      { word: 'Wall', korean: '벽', emoji: '🧱' },
      { word: 'Wan', korean: '창백한', emoji: '😰' },
      { word: 'Wand', korean: '지팡이', emoji: '🪄' },
      { word: 'Want', korean: '원하다', emoji: '🤲' },
      { word: 'War', korean: '전쟁', emoji: '⚔️' },
      { word: 'Ward', korean: '병동', emoji: '🏥' },
      { word: 'Ware', korean: '상품', emoji: '📦' },
      { word: 'Warm', korean: '따뜻한', emoji: '🔥' },
      { word: 'Warn', korean: '경고하다', emoji: '⚠️' },
      { word: 'Warp', korean: '휘다', emoji: '🌀' },
      { word: 'Wart', korean: '사마귀', emoji: '🔴' },
      { word: 'Wary', korean: '조심스러운', emoji: '👀' },
      { word: 'Wash', korean: '씻다', emoji: '🧼' },
      { word: 'Wasp', korean: '말벌', emoji: '🐝' },
      { word: 'Waste', korean: '낭비', emoji: '🗑️' },
      { word: 'Watch', korean: '시계', emoji: '⌚' },
      { word: 'Wave', korean: '파도', emoji: '🌊' },
      { word: 'Wax', korean: '왁스', emoji: '🕯️' },
    ],
  },
  {
    uppercase: 'X',
    lowercase: 'x',
    name: '엑스',
    words: [
      { word: 'X-ray', korean: '엑스레이', emoji: '🦴' },
      { word: 'Xylophone', korean: '실로폰', emoji: '🎹' },
      { word: 'Fox', korean: '여우', emoji: '🦊' },
      { word: 'Box', korean: '상자', emoji: '📦' },
      { word: 'Ax', korean: '도끼', emoji: '🪓' },
      { word: 'Fix', korean: '고치다', emoji: '🔧' },
      { word: 'Mix', korean: '섞다', emoji: '🔄' },
      { word: 'Six', korean: '6', emoji: '6️⃣' },
      { word: 'Max', korean: '최대', emoji: '⬆️' },
      { word: 'Tax', korean: '세금', emoji: '💸' },
      { word: 'Wax', korean: '왁스', emoji: '🕯️' },
      { word: 'Ox', korean: '소', emoji: '🐂' },
      { word: 'Lax', korean: '느슨한', emoji: '😌' },
      { word: 'Pox', korean: '천연두', emoji: '🩹' },
      { word: 'Rex', korean: '왕', emoji: '👑' },
      { word: 'Sex', korean: '성별', emoji: '👥' },
      { word: 'Tex', korean: '텍사스', emoji: '🤠' },
      { word: 'Vex', korean: '화나게 하다', emoji: '😠' },
      { word: 'Hex', korean: '주문', emoji: '🪄' },
      { word: 'Lux', korean: '럭스', emoji: '💡' },
      { word: 'Nix', korean: '없음', emoji: '❌' },
      { word: 'Pix', korean: '사진', emoji: '📷' },
      { word: 'Pox', korean: '두창', emoji: '🦠' },
      { word: 'Sax', korean: '색소폰', emoji: '🎷' },
      { word: 'Tux', korean: '턱시도', emoji: '🎩' },
      { word: 'Yex', korean: '딸꾹질', emoji: '😵' },
      { word: 'Zax', korean: '도끼', emoji: '🪓' },
      { word: 'Axe', korean: '도끼', emoji: '🪓' },
      { word: 'Apex', korean: '정점', emoji: '🔝' },
      { word: 'Index', korean: '색인', emoji: '📇' },
    ],
  },
  {
    uppercase: 'Y',
    lowercase: 'y',
    name: '와이',
    words: [
      { word: 'Yak', korean: '야크', emoji: '🐃' },
      { word: 'Yellow', korean: '노란색', emoji: '🟡' },
      { word: 'Yarn', korean: '실', emoji: '🧶' },
      { word: 'Yo-yo', korean: '요요', emoji: '🪀' },
      { word: 'You', korean: '너', emoji: '👤' },
      { word: 'Yes', korean: '네', emoji: '✅' },
      { word: 'Yay', korean: '야호', emoji: '🎉' },
      { word: 'Yam', korean: '고구마', emoji: '🍠' },
      { word: 'Yap', korean: '짖다', emoji: '🐕' },
      { word: 'Yard', korean: '마당', emoji: '🏡' },
      { word: 'Yarn', korean: '실', emoji: '🧶' },
      { word: 'Yawn', korean: '하품하다', emoji: '😴' },
      { word: 'Yea', korean: '예', emoji: '👍' },
      { word: 'Year', korean: '년', emoji: '📅' },
      { word: 'Yell', korean: '외치다', emoji: '📢' },
      { word: 'Yellow', korean: '노란색', emoji: '🟡' },
      { word: 'Yelp', korean: '짖다', emoji: '🐕' },
      { word: 'Yen', korean: '엔', emoji: '💴' },
      { word: 'Yeoman', korean: '하급 관리', emoji: '👨' },
      { word: 'Yep', korean: '응', emoji: '👍' },
      { word: 'Yes', korean: '네', emoji: '✅' },
      { word: 'Yet', korean: '아직', emoji: '⏳' },
      { word: 'Yew', korean: '주목', emoji: '🌲' },
      { word: 'Yid', korean: '유대인', emoji: '👤' },
      { word: 'Yin', korean: '음', emoji: '⚫' },
      { word: 'Yip', korean: '짧게 짖다', emoji: '🐕' },
      { word: 'Yob', korean: '불량배', emoji: '😠' },
      { word: 'Yodel', korean: '요들', emoji: '🎵' },
      { word: 'Yoga', korean: '요가', emoji: '🧘' },
    ],
  },
  {
    uppercase: 'Z',
    lowercase: 'z',
    name: '제드',
    words: [
      { word: 'Zebra', korean: '얼룩말', emoji: '🦓' },
      { word: 'Zoo', korean: '동물원', emoji: '🐾' },
      { word: 'Zip', korean: '지퍼', emoji: '🤐' },
      { word: 'Zero', korean: '영', emoji: '0️⃣' },
      { word: 'Zero', korean: '영', emoji: '0️⃣' },
      { word: 'Zap', korean: '쾅', emoji: '⚡' },
      { word: 'Zax', korean: '도끼', emoji: '🪓' },
      { word: 'Zed', korean: 'Z', emoji: '🔤' },
      { word: 'Zee', korean: 'Z', emoji: '🔤' },
      { word: 'Zen', korean: '선', emoji: '🧘' },
      { word: 'Zep', korean: '제프', emoji: '🚂' },
      { word: 'Zest', korean: '열정', emoji: '🔥' },
      { word: 'Zig', korean: '지그', emoji: '⚡' },
      { word: 'Zilch', korean: '아무것도', emoji: '❌' },
      { word: 'Zinc', korean: '아연', emoji: '⚗️' },
      { word: 'Zing', korean: '징', emoji: '⚡' },
      { word: 'Zion', korean: '시온', emoji: '⛰️' },
      { word: 'Zip', korean: '지퍼', emoji: '🤐' },
      { word: 'Zit', korean: '여드름', emoji: '🔴' },
      { word: 'Zizz', korean: '잠', emoji: '😴' },
      { word: 'Zo', korean: '동물', emoji: '🐾' },
      { word: 'Zoa', korean: '동물', emoji: '🐾' },
      { word: 'Zone', korean: '구역', emoji: '📍' },
      { word: 'Zoo', korean: '동물원', emoji: '🐾' },
      { word: 'Zoom', korean: '확대', emoji: '🔍' },
      { word: 'Zoot', korean: '줏', emoji: '👕' },
      { word: 'Zorb', korean: '좁', emoji: '⚽' },
      { word: 'Zouk', korean: '주크', emoji: '🎵' },
      { word: 'Zulu', korean: '줄루', emoji: '👤' },
      { word: 'Zzz', korean: '쿨쿨', emoji: '😴' },
    ],
  },
];

// 진행 상황 저장/불러오기 유틸 함수
export interface ProgressData {
  [letter: string]: {
    completed: boolean;
    stars: number; // 0-3
    practiced: boolean; // 쓰기 연습 했는지
  };
}

export const saveProgress = (letter: string, data: Partial<ProgressData[string]>) => {
  const current = getProgress();
  current[letter] = { ...current[letter], ...data };
  localStorage.setItem('alphabetProgress', JSON.stringify(current));
};

export const getProgress = (): ProgressData => {
  if (typeof window === 'undefined') return {};
  const saved = localStorage.getItem('alphabetProgress');
  return saved ? JSON.parse(saved) : {};
};

export const getLetterProgress = (letter: string) => {
  const progress = getProgress();
  return progress[letter] || { completed: false, stars: 0, practiced: false };
};

// 진행 상황 초기화 함수
export const resetProgress = () => {
  if (typeof window !== 'undefined') {
    localStorage.removeItem('alphabetProgress');
    return true;
  }
  return false;
};

