// 마인크래프트 테마 데이터 - 알파벳별 마인크래프트 블록/아이템/몹 이름
import { AlphabetData, Word } from './alphabetData';
import { getMinecraftImageUrl } from './minecraftImageUrls';

// 마인크래프트 단어 생성 헬퍼 함수 (이미지 URL 자동 추가)
function createMinecraftWord(word: string, korean: string, emoji: string): Word {
  const imageUrl = getMinecraftImageUrl(word);
  return {
    word,
    korean,
    emoji,
    ...(imageUrl && { imageUrl }), // 이미지 URL이 있으면 추가
  };
}

export const minecraftAlphabetData: AlphabetData[] = [
  {
    uppercase: 'A',
    lowercase: 'a',
    name: '에이',
    words: [
      createMinecraftWord('Apple', '사과', '🍎'),
      createMinecraftWord('Arrow', '화살', '🏹'),
      createMinecraftWord('Axe', '도끼', '🪓'),
      createMinecraftWord('Armor', '갑옷', '🛡️'),
      createMinecraftWord('Anvil', '모루', '⚒️'),
      createMinecraftWord('Acacia', '아카시아나무', '🌳'),
      createMinecraftWord('Allay', '앨레이', '✨'),
      createMinecraftWord('Axolotl', '아홀로틀', '🦎'),
      createMinecraftWord('Ancient Debris', '고대의 잔해', '⚫'),
      createMinecraftWord('Amethyst', '자수정', '💜'),
    ],
  },
  {
    uppercase: 'B',
    lowercase: 'b',
    name: '비',
    words: [
      createMinecraftWord('Bed', '침대', '🛏️'),
      createMinecraftWord('Bucket', '양동이', '🪣'),
      createMinecraftWord('Bow', '활', '🏹'),
      createMinecraftWord('Boat', '보트', '⛵'),
      createMinecraftWord('Block', '블록', '🧱'),
      createMinecraftWord('Brick', '벽돌', '🧱'),
      createMinecraftWord('Blaze', '블레이즈', '🔥'),
      createMinecraftWord('Bone', '뼈', '🦴'),
      createMinecraftWord('Beacon', '신호기', '📡'),
      createMinecraftWord('Bee', '벌', '🐝'),
    ],
  },
  {
    uppercase: 'C',
    lowercase: 'c',
    name: '씨',
    words: [
      createMinecraftWord('Crafting Table', '제작대', '🪵'),
      createMinecraftWord('Chest', '상자', '📦'),
      createMinecraftWord('Chicken', '닭', '🐔'),
      createMinecraftWord('Cow', '소', '🐄'),
      createMinecraftWord('Carrot', '당근', '🥕'),
      createMinecraftWord('Coal', '석탄', '⚫'),
      createMinecraftWord('Creeper', '크리퍼', '💥'),
      createMinecraftWord('Cobblestone', '조약돌', '🪨'),
      createMinecraftWord('Cookie', '쿠키', '🍪'),
      createMinecraftWord('Compass', '나침반', '🧭'),
    ],
  },
  {
    uppercase: 'D',
    lowercase: 'd',
    name: '디',
    words: [
      createMinecraftWord('Diamond', '다이아몬드', '💎'),
      createMinecraftWord('Door', '문', '🚪'),
      createMinecraftWord('Dirt', '흙', '🟫'),
      createMinecraftWord('Dragon', '엔더드래곤', '🐲'),
      createMinecraftWord('Dispenser', '발사기', '🎯'),
      createMinecraftWord('Dolphin', '돌고래', '🐬'),
      createMinecraftWord('Donkey', '당나귀', '🫏'),
      createMinecraftWord('Drowned', '드라운드', '🧟'),
      createMinecraftWord('Diorite', '섬록암', '⚪'),
      createMinecraftWord('Deepslate', '심층암', '⚫'),
    ],
  },
  {
    uppercase: 'E',
    lowercase: 'e',
    name: '이',
    words: [
      createMinecraftWord('Egg', '달걀', '🥚'),
      createMinecraftWord('Emerald', '에메랄드', '💚'),
      createMinecraftWord('Enchanting Table', '마법부여대', '✨'),
      createMinecraftWord('Enderman', '엔더맨', '👤'),
      createMinecraftWord('Ender Dragon', '엔더드래곤', '🐲'),
      createMinecraftWord('Eye of Ender', '엔더의눈', '👁️'),
      createMinecraftWord('Elder Guardian', '엘더 가디언', '🐟'),
      createMinecraftWord('Elytra', '겉날개', '🪽'),
      createMinecraftWord('End Crystal', '엔더 수정', '💎'),
      createMinecraftWord('Experience', '경험치', '✨'),
    ],
  },
  {
    uppercase: 'F',
    lowercase: 'f',
    name: '에프',
    words: [
      createMinecraftWord('Farm', '농장', '🌾'),
      createMinecraftWord('Furnace', '화로', '🔥'),
      createMinecraftWord('Fish', '물고기', '🐟'),
      createMinecraftWord('Flint', '부싯돌', '⚪'),
      createMinecraftWord('Fire', '불', '🔥'),
      createMinecraftWord('Fence', '울타리', '🚧'),
      createMinecraftWord('Fox', '여우', '🦊'),
      createMinecraftWord('Feather', '깃털', '🪶'),
      createMinecraftWord('Flower', '꽃', '🌸'),
      createMinecraftWord('Fishing Rod', '낚시대', '🎣'),
    ],
  },
  {
    uppercase: 'G',
    lowercase: 'g',
    name: '지',
    words: [
      createMinecraftWord('Glass', '유리', '🪟'),
      createMinecraftWord('Gold', '금', '🟡'),
      createMinecraftWord('Grass', '잔디', '🌱'),
      createMinecraftWord('Gravel', '자갈', '⚪'),
      createMinecraftWord('Gunpowder', '화약', '💥'),
      createMinecraftWord('Glowstone', '발광석', '💡'),
      createMinecraftWord('Ghast', '가스트', '👻'),
      createMinecraftWord('Goat', '염소', '🐐'),
      createMinecraftWord('Guardian', '가디언', '🐟'),
      createMinecraftWord('Golem', '골렘', '🤖'),
    ],
  },
  {
    uppercase: 'H',
    lowercase: 'h',
    name: '에이치',
    words: [
      createMinecraftWord('Hoe', '괭이', '🔨'),
      createMinecraftWord('Horse', '말', '🐴'),
      createMinecraftWord('Helmet', '투구', '🪖'),
      createMinecraftWord('House', '집', '🏠'),
      createMinecraftWord('Honey', '꿀', '🍯'),
      createMinecraftWord('Hay Bale', '건초더미', '🌾'),
      createMinecraftWord('Hoglin', '호글린', '🐗'),
      createMinecraftWord('Hopper', '깔때기', '🪣'),
      createMinecraftWord('Husk', '허스크', '🧟'),
      createMinecraftWord('Honeycomb', '벌집', '🍯'),
    ],
  },
  {
    uppercase: 'I',
    lowercase: 'i',
    name: '아이',
    words: [
      createMinecraftWord('Iron', '철', '⚙️'),
      createMinecraftWord('Ingot', '주괴', '⚙️'),
      createMinecraftWord('Item', '아이템', '📦'),
      createMinecraftWord('Illager', '약탈자', '⚔️'),
      createMinecraftWord('Ice', '얼음', '🧊'),
      createMinecraftWord('Iron Golem', '철 골렘', '🤖'),
      createMinecraftWord('Ink Sac', '먹물 주머니', '🖤'),
      createMinecraftWord('Iron Ore', '철 광석', '⚙️'),
      createMinecraftWord('Illusioner', '환상술사', '🎭'),
      createMinecraftWord('Item Frame', '아이템 액자', '🖼️'),
    ],
  },
  {
    uppercase: 'J',
    lowercase: 'j',
    name: '제이',
    words: [
      createMinecraftWord('Jungle', '정글', '🌴'),
      createMinecraftWord('Jack-o\'-lantern', '잭오랜턴', '🎃'),
      createMinecraftWord('Jukebox', '주크박스', '📻'),
      createMinecraftWord('Jellyfish', '해파리', '🎐'),
      createMinecraftWord('Jigsaw Block', '직소 블록', '🧩'),
    ],
  },
  {
    uppercase: 'K',
    lowercase: 'k',
    name: '케이',
    words: [
      createMinecraftWord('Kelp', '다시마', '🌿'),
      createMinecraftWord('Knight', '기사', '⚔️'),
      createMinecraftWord('Key', '열쇠', '🔑'),
      createMinecraftWord('Killer Rabbit', '킬러 래빗', '🐰'),
      createMinecraftWord('Knowledge Book', '지식 책', '📚'),
    ],
  },
  {
    uppercase: 'L',
    lowercase: 'l',
    name: '엘',
    words: [
      createMinecraftWord('Log', '나무', '🪵'),
      createMinecraftWord('Leather', '가죽', '🐄'),
      createMinecraftWord('Lapis', '청금석', '💙'),
      createMinecraftWord('Ladder', '사다리', '🪜'),
      createMinecraftWord('Lava', '용암', '🌋'),
      createMinecraftWord('Lantern', '랜턴', '🏮'),
      createMinecraftWord('Llama', '라마', '🦙'),
      createMinecraftWord('Lilac', '라일락', '🌸'),
      createMinecraftWord('Lily Pad', '수련 잎', '🌿'),
      createMinecraftWord('Lead', '끈', '🧵'),
    ],
  },
  {
    uppercase: 'M',
    lowercase: 'm',
    name: '엠',
    words: [
      createMinecraftWord('Minecraft', '마인크래프트', '🎮'),
      createMinecraftWord('Mine', '광산', '⛏️'),
      createMinecraftWord('Mob', '몹', '👹'),
      createMinecraftWord('Monster', '몬스터', '👹'),
      createMinecraftWord('Mushroom', '버섯', '🍄'),
      createMinecraftWord('Minecart', '광산수레', '🚂'),
      createMinecraftWord('Magma Cube', '마그마 큐브', '🔥'),
      createMinecraftWord('Mutton', '양고기', '🥩'),
      createMinecraftWord('Music Disc', '음반', '💿'),
      createMinecraftWord('Moss', '이끼', '🌿'),
    ],
  },
  {
    uppercase: 'N',
    lowercase: 'n',
    name: '엔',
    words: [
      createMinecraftWord('Nether', '네더', '🔥'),
      createMinecraftWord('Netherite', '네더라이트', '⚫'),
      createMinecraftWord('Note Block', '음악블록', '🎵'),
      createMinecraftWord('Nether Portal', '네더포털', '🌀'),
      createMinecraftWord('Nether Star', '네더의별', '⭐'),
      createMinecraftWord('Nautilus Shell', '앵무조개', '🐚'),
      createMinecraftWord('Nether Brick', '네더 벽돌', '🧱'),
      createMinecraftWord('Nether Wart', '네더 사마귀', '🟣'),
      createMinecraftWord('Nurse', '간호사', '💉'),
    ],
  },
  {
    uppercase: 'O',
    lowercase: 'o',
    name: '오',
    words: [
      createMinecraftWord('Oak', '참나무', '🌳'),
      createMinecraftWord('Obsidian', '흑요석', '⚫'),
      createMinecraftWord('Ore', '광석', '💎'),
      createMinecraftWord('Ocelot', '오셀롯', '🐱'),
      createMinecraftWord('Oven', '화로', '🔥'),
      createMinecraftWord('Oxeye Daisy', '데이지', '🌼'),
      createMinecraftWord('Orange', '오렌지', '🟠'),
    ],
  },
  {
    uppercase: 'P',
    lowercase: 'p',
    name: '피',
    words: [
      createMinecraftWord('Pickaxe', '곡괭이', '⛏️'),
      createMinecraftWord('Pig', '돼지', '🐷'),
      createMinecraftWord('Player', '플레이어', '👤'),
      createMinecraftWord('Pumpkin', '호박', '🎃'),
      createMinecraftWord('Portal', '포털', '🌀'),
      createMinecraftWord('Potato', '감자', '🥔'),
      createMinecraftWord('Phantom', '팬텀', '👻'),
      createMinecraftWord('Panda', '판다', '🐼'),
      createMinecraftWord('Painting', '그림', '🖼️'),
      createMinecraftWord('Pufferfish', '복어', '🐡'),
    ],
  },
  {
    uppercase: 'Q',
    lowercase: 'q',
    name: '큐',
    words: [
      createMinecraftWord('Quartz', '석영', '💎'),
      createMinecraftWord('Quiver', '화살통', '🏹'),
      createMinecraftWord('Quartz Block', '석영 블록', '⚪'),
      createMinecraftWord('Quartz Pillar', '석영 기둥', '⚪'),
    ],
  },
  {
    uppercase: 'R',
    lowercase: 'r',
    name: '알',
    words: [
      createMinecraftWord('Redstone', '레드스톤', '🔴'),
      createMinecraftWord('Rail', '레일', '🚂'),
      createMinecraftWord('Rock', '돌', '🪨'),
      createMinecraftWord('Redstone Torch', '레드스톤횃불', '🔥'),
      createMinecraftWord('Rotten Flesh', '썩은고기', '🥩'),
      createMinecraftWord('Rabbit', '토끼', '🐰'),
      createMinecraftWord('Ravager', '파괴수', '🐂'),
      createMinecraftWord('Redstone Lamp', '레드스톤 램프', '💡'),
      createMinecraftWord('Repeater', '리피터', '🔁'),
      createMinecraftWord('Rose', '장미', '🌹'),
    ],
  },
  {
    uppercase: 'S',
    lowercase: 's',
    name: '에스',
    words: [
      createMinecraftWord('Stone', '돌', '🪨'),
      createMinecraftWord('Sword', '검', '⚔️'),
      createMinecraftWord('Sheep', '양', '🐑'),
      createMinecraftWord('Steve', '스티브', '👤'),
      createMinecraftWord('Sand', '모래', '🏖️'),
      createMinecraftWord('Skeleton', '스켈레톤', '💀'),
      createMinecraftWord('Shovel', '삽', '🪣'),
      createMinecraftWord('Spider', '거미', '🕷️'),
      createMinecraftWord('Salmon', '연어', '🐟'),
      createMinecraftWord('Slime', '슬라임', '🟢'),
    ],
  },
  {
    uppercase: 'T',
    lowercase: 't',
    name: '티',
    words: [
      createMinecraftWord('Tree', '나무', '🌳'),
      createMinecraftWord('Torch', '횃불', '🔥'),
      createMinecraftWord('Tool', '도구', '🔧'),
      createMinecraftWord('TNT', 'TNT', '💣'),
      createMinecraftWord('Table', '테이블', '🪵'),
      createMinecraftWord('Trapdoor', '함정문', '🚪'),
      createMinecraftWord('Turtle', '거북이', '🐢'),
      createMinecraftWord('Tadpole', '올챙이', '🐸'),
      createMinecraftWord('Trident', '삼지창', '🔱'),
      createMinecraftWord('Totem', '토템', '🪬'),
    ],
  },
  {
    uppercase: 'U',
    lowercase: 'u',
    name: '유',
    words: [
      createMinecraftWord('Underwater', '물속', '🌊'),
      createMinecraftWord('Underground', '지하', '🕳️'),
      createMinecraftWord('Underground', '지하', '🕳️'),
      createMinecraftWord('Underwater', '물속', '🌊'),
      createMinecraftWord('Underground', '지하', '🕳️'),
    ],
  },
  {
    uppercase: 'V',
    lowercase: 'v',
    name: '브이',
    words: [
      createMinecraftWord('Villager', '주민', '👤'),
      createMinecraftWord('Vines', '덩굴', '🌿'),
      createMinecraftWord('Village', '마을', '🏘️'),
      createMinecraftWord('Vex', '벡스', '👻'),
      createMinecraftWord('Vindicator', '학살자', '⚔️'),
    ],
  },
  {
    uppercase: 'W',
    lowercase: 'w',
    name: '더블유',
    words: [
      createMinecraftWord('Wood', '나무', '🪵'),
      createMinecraftWord('Water', '물', '💧'),
      createMinecraftWord('Wheat', '밀', '🌾'),
      createMinecraftWord('Wolf', '늑대', '🐺'),
      createMinecraftWord('Wool', '털', '🐑'),
      createMinecraftWord('Wooden Sword', '나무검', '⚔️'),
      createMinecraftWord('Warden', '워든', '👹'),
      createMinecraftWord('Witch', '마녀', '🧙'),
      createMinecraftWord('Wither', '위더', '💀'),
      createMinecraftWord('Wither Skeleton', '위더 스켈레톤', '💀'),
    ],
  },
  {
    uppercase: 'X',
    lowercase: 'x',
    name: '엑스',
    words: [
      createMinecraftWord('Xp', '경험치', '✨'),
      createMinecraftWord('X-Ray', '엑스레이', '🔍'),
      createMinecraftWord('Xp', '경험치', '✨'),
      createMinecraftWord('X-Ray', '엑스레이', '🔍'),
      createMinecraftWord('Xp', '경험치', '✨'),
    ],
  },
  {
    uppercase: 'Y',
    lowercase: 'y',
    name: '와이',
    words: [
      createMinecraftWord('Yellow', '노란색', '🟡'),
      createMinecraftWord('Yarn', '실', '🧵'),
      createMinecraftWord('Yellow', '노란색', '🟡'),
      createMinecraftWord('Yarn', '실', '🧵'),
      createMinecraftWord('Yellow', '노란색', '🟡'),
    ],
  },
  {
    uppercase: 'Z',
    lowercase: 'z',
    name: '제드',
    words: [
      createMinecraftWord('Zombie', '좀비', '🧟'),
      createMinecraftWord('Zombie Pigman', '좀비 피그맨', '🧟'),
      createMinecraftWord('Zombie Villager', '좀비 주민', '🧟'),
      createMinecraftWord('Zombie Horse', '좀비 말', '🧟'),
      createMinecraftWord('Zombie', '좀비', '🧟'),
    ],
  },
];
