// 포켓몬스터 테마 데이터 - 알파벳별 포켓몬 이름
import { AlphabetData, Word } from './alphabetData';
import { getPokemonImageUrl } from './pokemonImageUrls';

// 포켓몬 단어 생성 헬퍼 함수 (이미지 URL 자동 추가)
function createPokemonWord(word: string, korean: string, emoji: string): Word {
  const imageUrl = getPokemonImageUrl(word);
  return {
    word,
    korean,
    emoji,
    ...(imageUrl && { imageUrl }), // 이미지 URL이 있으면 추가
  };
}

export const pokemonAlphabetData: AlphabetData[] = [
  {
    uppercase: 'A',
    lowercase: 'a',
    name: '에이',
    words: [
      createPokemonWord('Abra', '캐이시', '🧙'),
      createPokemonWord('Arbok', '아보크', '🐍'),
      createPokemonWord('Articuno', '프리저', '❄️'),
      createPokemonWord('Aerodactyl', '프테라', '🦕'),
      createPokemonWord('Alakazam', '후딘', '✨'),
      createPokemonWord('Aipom', '에이팜', '🐒'),
      createPokemonWord('Ampharos', '전룡', '⚡'),
      createPokemonWord('Ariados', '아리아도스', '🕷️'),
      createPokemonWord('Azumarill', '마릴리', '🐰'),
      createPokemonWord('Azurill', '루리리', '💧'),
    ],
  },
  {
    uppercase: 'B',
    lowercase: 'b',
    name: '비',
    words: [
      createPokemonWord('Bulbasaur', '이상해씨', '🌱'),
      createPokemonWord('Butterfree', '버터플', '🦋'),
      createPokemonWord('Beedrill', '독침붕', '🐝'),
      createPokemonWord('Blastoise', '거북왕', '🐢'),
      createPokemonWord('Bellsprout', '야돈', '🌿'),
      createPokemonWord('Blissey', '해피너스', '💕'),
      createPokemonWord('Breloom', '버섯모', '🍄'),
      createPokemonWord('Bayleef', '베이리프', '🌿'),
      createPokemonWord('Blaziken', '번치코', '🔥'),
      createPokemonWord('Buneary', '이어롤', '🐰'),
    ],
  },
  {
    uppercase: 'C',
    lowercase: 'c',
    name: '씨',
    words: [
      createPokemonWord('Charmander', '파이리', '🔥'),
      createPokemonWord('Charizard', '리자몽', '🐲'),
      createPokemonWord('Caterpie', '캐터피', '🐛'),
      createPokemonWord('Clefairy', '피카츄', '⭐'),
      createPokemonWord('Cloyster', '파르셀', '🐚'),
      createPokemonWord('Chikorita', '치코리타', '🌱'),
      createPokemonWord('Cyndaquil', '브케인', '🔥'),
      createPokemonWord('Croconaw', '엘리게이', '🐊'),
      createPokemonWord('Celebi', '세레비', '🌿'),
      createPokemonWord('Combusken', '영치코', '🔥'),
    ],
  },
  {
    uppercase: 'D',
    lowercase: 'd',
    name: '디',
    words: [
      createPokemonWord('Dragonite', '망나뇽', '🐉'),
      createPokemonWord('Dratini', '미뇽', '🐉'),
      createPokemonWord('Dugtrio', '디그다', '🕳️'),
      createPokemonWord('Dewgong', '쥬레곤', '🐋'),
      createPokemonWord('Ditto', '메타몽', '💫'),
      createPokemonWord('Dunsparce', '노고치', '🦎'),
      createPokemonWord('Donphan', '코코리', '🐘'),
      createPokemonWord('Delibird', '딜리버드', '🎁'),
      createPokemonWord('Delcatty', '델케티', '🐱'),
      createPokemonWord('Dustox', '독케일', '🦋'),
    ],
  },
  {
    uppercase: 'E',
    lowercase: 'e',
    name: '이',
    words: [
      createPokemonWord('Eevee', '이브이', '🦊'),
      createPokemonWord('Ekans', '아보', '🐍'),
      createPokemonWord('Electabuzz', '에레브', '⚡'),
      createPokemonWord('Electrode', '붐볼', '⚡'),
      createPokemonWord('Exeggcute', '탕구리', '🥚'),
      createPokemonWord('Exeggutor', '나시', '🥥'),
      createPokemonWord('Elekid', '에레키드', '⚡'),
      createPokemonWord('Entei', '앤테이', '🔥'),
      createPokemonWord('Espeon', '에브이', '💜'),
      createPokemonWord('Empoleon', '엠페르트', '🐧'),
    ],
  },
  {
    uppercase: 'F',
    lowercase: 'f',
    name: '에프',
    words: [
      createPokemonWord('Flareon', '부스터', '🔥'),
      createPokemonWord('Farfetchd', '파오리', '🦆'),
      createPokemonWord('Fearow', '깨비참', '🦅'),
      createPokemonWord('Feraligatr', '장크로다일', '🐊'),
      createPokemonWord('Forretress', '피콘', '🛡️'),
      createPokemonWord('Furret', '레트라', '🐭'),
      createPokemonWord('Flaaffy', '다꼬리', '🐑'),
      createPokemonWord('Froslass', '눈여아', '❄️'),
      createPokemonWord('Flygon', '플라이곤', '🦎'),
      createPokemonWord('Frosmoth', '모스노우', '❄️'),
    ],
  },
  {
    uppercase: 'G',
    lowercase: 'g',
    name: '지',
    words: [
      createPokemonWord('Gengar', '팬텀', '👻'),
      createPokemonWord('Golbat', '골뱃', '🦇'),
      createPokemonWord('Golduck', '고라파덕', '🦆'),
      createPokemonWord('Golem', '딱구리', '🪨'),
      createPokemonWord('Growlithe', '가디', '🐕'),
      createPokemonWord('Glaceon', '글레이시아', '❄️'),
      createPokemonWord('Garchomp', '한카리아스', '🦈'),
      createPokemonWord('Gallade', '엘레이드', '⚔️'),
      createPokemonWord('Giratina', '기라티나', '🌑'),
      createPokemonWord('Gyarados', '갸라도스', '🐉'),
    ],
  },
  {
    uppercase: 'H',
    lowercase: 'h',
    name: '에이치',
    words: [
      createPokemonWord('Haunter', '고우스트', '👻'),
      createPokemonWord('Hitmonchan', '홍수몬', '👊'),
      createPokemonWord('Hitmonlee', '시라소몬', '🦵'),
      createPokemonWord('Horsea', '씨드라', '🐴'),
      createPokemonWord('Hypno', '슬리프', '🧙'),
      createPokemonWord('Hoothoot', '부우부', '🦉'),
      createPokemonWord('Hoppip', '통통코', '🎈'),
      createPokemonWord('Heracross', '헤라크로스', '🪲'),
      createPokemonWord('Houndoom', '헬가', '🐕'),
      createPokemonWord('Hariyama', '하리뭉', '👊'),
    ],
  },
  {
    uppercase: 'I',
    lowercase: 'i',
    name: '아이',
    words: [
      createPokemonWord('Ivysaur', '이상해풀', '🌿'),
      createPokemonWord('Igglybuff', '푸푸린', '💗'),
      createPokemonWord('Illumise', '일레도리자드', '💡'),
      createPokemonWord('Infernape', '초염몽', '🔥'),
      createPokemonWord('Inkay', '만마드', '🐙'),
      createPokemonWord('Inteleon', '인텔리레온', '🦎'),
      createPokemonWord('Incineroar', '어흥염', '🔥'),
      createPokemonWord('Ivysaur', '이상해풀', '🌿'),
      createPokemonWord('Igglybuff', '푸푸린', '💗'),
      createPokemonWord('Illumise', '일레도리자드', '💡'),
    ],
  },
  {
    uppercase: 'J',
    lowercase: 'j',
    name: '제이',
    words: [
      createPokemonWord('Jigglypuff', '푸린', '💗'),
      createPokemonWord('Jolteon', '쥬피썬더', '⚡'),
      createPokemonWord('Jynx', '루주라', '🧊'),
      createPokemonWord('Jumpluff', '에이팜', '🎈'),
      createPokemonWord('Jirachi', '지라치', '⭐'),
      createPokemonWord('Joltik', '저리어', '⚡'),
      createPokemonWord('Jangmo-o', '짜랑꼬', '🐲'),
      createPokemonWord('Jellicent', '로파파', '💧'),
      createPokemonWord('Jirachi', '지라치', '⭐'),
      createPokemonWord('Jynx', '루주라', '🧊'),
    ],
  },
  {
    uppercase: 'K',
    lowercase: 'k',
    name: '케이',
    words: [
      createPokemonWord('Kadabra', '윤겔라', '🧙'),
      createPokemonWord('Kakuna', '딱충이', '🐛'),
      createPokemonWord('Kangaskhan', '캥카', '🦘'),
      createPokemonWord('Kingler', '킹ler', '🦀'),
      createPokemonWord('Koffing', '또가스', '💨'),
      createPokemonWord('Kirlia', '키르리아', '💃'),
      createPokemonWord('Kecleon', '켈리몬', '🦎'),
      createPokemonWord('Kyogre', '가이오가', '🌊'),
      createPokemonWord('Klefki', '클레피', '🔑'),
      createPokemonWord('Komala', '코마루', '🐨'),
    ],
  },
  {
    uppercase: 'L',
    lowercase: 'l',
    name: '엘',
    words: [
      createPokemonWord('Lapras', '라프라스', '🐋'),
      createPokemonWord('Lickitung', '내루미', '👅'),
      createPokemonWord('Lucario', '루카리오', '🐺'),
      createPokemonWord('Lugia', '루기아', '🐉'),
      createPokemonWord('Lunatone', '루나톤', '🌙'),
      createPokemonWord('Luxray', '렌트라', '⚡'),
      createPokemonWord('Lycanroc', '루가루암', '🐺'),
      createPokemonWord('Litten', '나옹', '🔥'),
      createPokemonWord('Lurantis', '라라티스', '🦗'),
      createPokemonWord('Latias', '라티아스', '🐉'),
    ],
  },
  {
    uppercase: 'M',
    lowercase: 'm',
    name: '엠',
    words: [
      createPokemonWord('Machamp', '괴력몬', '💪'),
      createPokemonWord('Machoke', '근육몬', '💪'),
      createPokemonWord('Machop', '알통몬', '💪'),
      createPokemonWord('Magikarp', '잉어킹', '🐟'),
      createPokemonWord('Magnemite', '코일', '🧲'),
      createPokemonWord('Magneton', '레어코일', '🧲'),
      createPokemonWord('Mamoswine', '맘모꾸리', '🐷'),
      createPokemonWord('Manaphy', '마나피', '💧'),
      createPokemonWord('Marshadow', '마샤도', '👻'),
      createPokemonWord('Mawile', '입치트', '😈'),
    ],
  },
  {
    uppercase: 'N',
    lowercase: 'n',
    name: '엔',
    words: [
      createPokemonWord('Nidoking', '니드킹', '👑'),
      createPokemonWord('Nidoqueen', '니드퀸', '👸'),
      createPokemonWord('Nidoran', '니드런', '🐰'),
      createPokemonWord('Ninetales', '나인테일', '🦊'),
      createPokemonWord('Noctowl', '야부엉', '🦉'),
      createPokemonWord('Nuzleaf', '다탕구', '🌿'),
      createPokemonWord('Nihilego', '우츠보트', '👽'),
      createPokemonWord('Noivern', '음번', '🦇'),
      createPokemonWord('Naganadel', '아고용', '🐛'),
      createPokemonWord('Necrozma', '네크로즈마', '💎'),
    ],
  },
  {
    uppercase: 'O',
    lowercase: 'o',
    name: '오',
    words: [
      createPokemonWord('Oddish', '뚜벅쵸', '🌿'),
      createPokemonWord('Omanyte', '암나이트', '🐚'),
      createPokemonWord('Omastar', '암스타', '🐚'),
      createPokemonWord('Onix', '롱스톤', '🪨'),
      createPokemonWord('Octillery', '대포무노', '🐙'),
      createPokemonWord('Oshawott', '수댕이', '💧'),
      createPokemonWord('Oranguru', '네모카', '🐒'),
      createPokemonWord('Obstagoon', '갓고우', '🐺'),
      createPokemonWord('Oricorio', '춤추새', '🕺'),
      createPokemonWord('Oddish', '뚜벅쵸', '🌿'),
    ],
  },
  {
    uppercase: 'P',
    lowercase: 'p',
    name: '피',
    words: [
      createPokemonWord('Pikachu', '피카츄', '⚡'),
      createPokemonWord('Pidgeot', '피죤투', '🦅'),
      createPokemonWord('Pidgeotto', '피죤', '🦅'),
      createPokemonWord('Pidgey', '구구', '🦅'),
      createPokemonWord('Pinsir', '쁘사이저', '🪲'),
      createPokemonWord('Poliwag', '발챙이', '💧'),
      createPokemonWord('Poliwhirl', '슈륙챙이', '💧'),
      createPokemonWord('Poliwrath', '강챙이', '💪'),
      createPokemonWord('Ponyta', '포니타', '🐴'),
      createPokemonWord('Primeape', '성원숭', '🐒'),
    ],
  },
  {
    uppercase: 'Q',
    lowercase: 'q',
    name: '큐',
    words: [
      createPokemonWord('Quagsire', '누오', '🐸'),
      createPokemonWord('Quilava', '마그케인', '🔥'),
      createPokemonWord('Qwilfish', '침바루', '🐟'),
      createPokemonWord('Quaxly', '꼬렛', '🦆'),
      createPokemonWord('Quaxwell', '꼬렛', '🦆'),
      createPokemonWord('Quaquaval', '꼬렛', '🦆'),
      createPokemonWord('Quagsire', '누오', '🐸'),
      createPokemonWord('Quilava', '마그케인', '🔥'),
      createPokemonWord('Qwilfish', '침바루', '🐟'),
      createPokemonWord('Quagsire', '누오', '🐸'),
    ],
  },
  {
    uppercase: 'R',
    lowercase: 'r',
    name: '알',
    words: [
      createPokemonWord('Raichu', '라이츄', '⚡'),
      createPokemonWord('Rapidash', '날쌩마', '🐴'),
      createPokemonWord('Raticate', '레트라', '🐭'),
      createPokemonWord('Rattata', '꼬렛', '🐭'),
      createPokemonWord('Rayquaza', '레쿠쟈', '🐉'),
      createPokemonWord('Regice', '레지아이스', '❄️'),
      createPokemonWord('Regirock', '레지락', '🪨'),
      createPokemonWord('Registeel', '레지스틸', '⚙️'),
      createPokemonWord('Riolu', '리오르', '🐺'),
      createPokemonWord('Roserade', '로즈레이드', '🌹'),
    ],
  },
  {
    uppercase: 'S',
    lowercase: 's',
    name: '에스',
    words: [
      createPokemonWord('Squirtle', '꼬부기', '🐢'),
      createPokemonWord('Scyther', '스라크', '🦗'),
      createPokemonWord('Starmie', '아쿠스타', '⭐'),
      createPokemonWord('Staryu', '별가사리', '⭐'),
      createPokemonWord('Snorlax', '잠만보', '😴'),
      createPokemonWord('Sceptile', '나무킹', '🦎'),
      createPokemonWord('Swampert', '대짱이', '🐸'),
      createPokemonWord('Salamence', '보만다', '🐉'),
      createPokemonWord('Shaymin', '쉐이미', '🌿'),
      createPokemonWord('Serperior', '샤로다', '🐍'),
    ],
  },
  {
    uppercase: 'T',
    lowercase: 't',
    name: '티',
    words: [
      createPokemonWord('Tauros', '켄타로스', '🐂'),
      createPokemonWord('Tangela', '덩쿠리', '🌿'),
      createPokemonWord('Tentacool', '발챙이', '🐙'),
      createPokemonWord('Tentacruel', '독파리', '🐙'),
      createPokemonWord('Togepi', '토게피', '🥚'),
      createPokemonWord('Torchic', '아차모', '🔥'),
      createPokemonWord('Treecko', '나무지기', '🦎'),
      createPokemonWord('Typhlosion', '블레이범', '🔥'),
      createPokemonWord('Tyrantrum', '견고라스', '🦖'),
      createPokemonWord('Talonflame', '화살꼬빈', '🔥'),
    ],
  },
  {
    uppercase: 'U',
    lowercase: 'u',
    name: '유',
    words: [
      createPokemonWord('Umbreon', '블래키', '🌙'),
      createPokemonWord('Ursaring', '링곰', '🐻'),
      createPokemonWord('Unown', '안농', '❓'),
      createPokemonWord('Ursaluna', '다다미', '🐻'),
      createPokemonWord('Urshifu', '우라오스', '🐻'),
      createPokemonWord('Umbreon', '블래키', '🌙'),
      createPokemonWord('Ursaring', '링곰', '🐻'),
      createPokemonWord('Unown', '안농', '❓'),
      createPokemonWord('Ursaluna', '다다미', '🐻'),
      createPokemonWord('Urshifu', '우라오스', '🐻'),
    ],
  },
  {
    uppercase: 'V',
    lowercase: 'v',
    name: '브이',
    words: [
      createPokemonWord('Vaporeon', '샤미드', '💧'),
      createPokemonWord('Venomoth', '도나리', '🦋'),
      createPokemonWord('Venonat', '콘팡', '🦟'),
      createPokemonWord('Venusaur', '이상해꽃', '🌺'),
      createPokemonWord('Victreebel', '우츠동', '🌿'),
      createPokemonWord('Vileplume', '라플레시아', '🌺'),
      createPokemonWord('Volcarona', '불카모스', '🔥'),
      createPokemonWord('Vanilluxe', '바닐리치', '🍦'),
      createPokemonWord('Vespiquen', '비퀸', '🐝'),
      createPokemonWord('Vibrava', '비브라바', '🦗'),
    ],
  },
  {
    uppercase: 'W',
    lowercase: 'w',
    name: '더블유',
    words: [
      createPokemonWord('Wartortle', '어니부기', '🐢'),
      createPokemonWord('Weedle', '뿔충이', '🐛'),
      createPokemonWord('Weepinbell', '우츠동', '🌿'),
      createPokemonWord('Weezing', '또도가스', '💨'),
      createPokemonWord('Wigglytuff', '푸크린', '💗'),
      createPokemonWord('Wobbuffet', '마자용', '👊'),
      createPokemonWord('Wurmple', '도토링', '🐛'),
      createPokemonWord('Wailord', '고래왕', '🐋'),
      createPokemonWord('Whiscash', '메깅', '🐟'),
      createPokemonWord('Wingull', '갈모매', '🦅'),
    ],
  },
  {
    uppercase: 'X',
    lowercase: 'x',
    name: '엑스',
    words: [
      createPokemonWord('Xatu', '네이티오', '🦅'),
      createPokemonWord('Xerneas', '제르네아스', '🦌'),
      createPokemonWord('Xurkitree', '전수목', '⚡'),
      createPokemonWord('Xatu', '네이티오', '🦅'),
      createPokemonWord('Xerneas', '제르네아스', '🦌'),
      createPokemonWord('Xurkitree', '전수목', '⚡'),
      createPokemonWord('Xatu', '네이티오', '🦅'),
      createPokemonWord('Xerneas', '제르네아스', '🦌'),
      createPokemonWord('Xurkitree', '전수목', '⚡'),
      createPokemonWord('Xatu', '네이티오', '🦅'),
    ],
  },
  {
    uppercase: 'Y',
    lowercase: 'y',
    name: '와이',
    words: [
      createPokemonWord('Yanma', '왕자리', '🦟'),
      createPokemonWord('Yveltal', '이벨타르', '🐉'),
      createPokemonWord('Yamper', '멍파치', '🐕'),
      createPokemonWord('Yanmega', '메가자리', '🦟'),
      createPokemonWord('Yungoos', '누니머기', '🐀'),
      createPokemonWord('Yanma', '왕자리', '🦟'),
      createPokemonWord('Yveltal', '이벨타르', '🐉'),
      createPokemonWord('Yamper', '멍파치', '🐕'),
      createPokemonWord('Yanmega', '메가자리', '🦟'),
      createPokemonWord('Yungoos', '누니머기', '🐀'),
    ],
  },
  {
    uppercase: 'Z',
    lowercase: 'z',
    name: '제드',
    words: [
      createPokemonWord('Zapdos', '썬더', '⚡'),
      createPokemonWord('Zubat', '주뱃', '🦇'),
      createPokemonWord('Zangoose', '쟝고', '🐱'),
      createPokemonWord('Zigzagoon', '지그제구리', '🐀'),
      createPokemonWord('Zoroark', '조로아크', '🐺'),
      createPokemonWord('Zorua', '조로아', '🐺'),
      createPokemonWord('Zygarde', '지가르데', '🐉'),
      createPokemonWord('Zacian', '자시안', '⚔️'),
      createPokemonWord('Zamazenta', '자마젠타', '🛡️'),
      createPokemonWord('Zekrom', '제크로무', '⚡'),
    ],
  },
];

