// 스타크래프트 1 테마 데이터 - 실제 게임의 유닛과 건물 이름
// 참고: https://m.blog.naver.com/suwon0917/100149522589
import { AlphabetData, Word } from './alphabetData';
import { getStarcraftImageUrl } from './starcraftImageUrls';

// 스타크래프트 단어 생성 헬퍼 함수 (이미지 URL 자동 추가)
function createStarcraftWord(word: string, korean: string, emoji: string): Word {
  const imageUrl = getStarcraftImageUrl(word);
  return {
    word,
    korean,
    emoji,
    ...(imageUrl && { imageUrl }), // 이미지 URL이 있으면 추가
  };
}

export const starcraftAlphabetData: AlphabetData[] = [
  {
    uppercase: 'A',
    lowercase: 'a',
    name: '에이',
    words: [
      createStarcraftWord('Arbiter', '아비터', '🛸'),
      createStarcraftWord('Archon', '아콘', '⚡'),
      createStarcraftWord('Academy', '아카데미', '🏛️'),
      createStarcraftWord('Armory', '무기고', '⚙️'),
      createStarcraftWord('Assimilator', '어시밀레이터', '💎'),
      createStarcraftWord('Attack', '공격', '⚔️'),
      createStarcraftWord('Air', '공중', '✈️'),
      createStarcraftWord('Alien', '외계인', '👽'),
      createStarcraftWord('Ammo', '탄약', '🔫'),
      createStarcraftWord('Armor', '장갑', '🛡️'),
    ],
  },
  {
    uppercase: 'B',
    lowercase: 'b',
    name: '비',
    words: [
      { word: 'Barracks', korean: '병영', emoji: '🏭' },
      { word: 'Battlecruiser', korean: '전투순양함', emoji: '🚢' },
      { word: 'Broodling', korean: '브루들링', emoji: '🐛' },
      { word: 'Bunker', korean: '벙커', emoji: '🏰' },
      { word: 'Burrow', korean: '땅굴', emoji: '🕳️' },
      { word: 'Build', korean: '건설', emoji: '🔨' },
      { word: 'Base', korean: '기지', emoji: '🏰' },
      { word: 'Beacon', korean: '신호기', emoji: '📡' },
      { word: 'Blink', korean: '점멸', emoji: '✨' },
      { word: 'Breed', korean: '번식', emoji: '🥚' },
    ],
  },
  {
    uppercase: 'C',
    lowercase: 'c',
    name: '씨',
    words: [
      { word: 'Carrier', korean: '캐리어', emoji: '✈️' },
      { word: 'Command Center', korean: '사령부', emoji: '🏢' },
      { word: 'Corsair', korean: '커세어', emoji: '🛩️' },
      { word: 'Cybernetics Core', korean: '사이버네틱스 코어', emoji: '🔬' },
      { word: 'Creep', korean: '크립', emoji: '🟣' },
      { word: 'Cocoon', korean: '번데기', emoji: '🪲' },
      { word: 'Cannon', korean: '포탑', emoji: '🔫' },
      { word: 'Cloak', korean: '은폐', emoji: '👻' },
      { word: 'Chrono', korean: '시간', emoji: '⏱️' },
      { word: 'Comsat', korean: '통신위성', emoji: '🛰️' },
    ],
  },
  {
    uppercase: 'D',
    lowercase: 'd',
    name: '디',
    words: [
      { word: 'Dragoon', korean: '드라군', emoji: '🤖' },
      { word: 'Dropship', korean: '수송선', emoji: '🚁' },
      { word: 'Dark Templar', korean: '다크 템플러', emoji: '⚔️' },
      { word: 'Defiler', korean: '디파일러', emoji: '🧪' },
      { word: 'Devourer', korean: '데보러', emoji: '🦟' },
      { word: 'Drone', korean: '드론', emoji: '🔧' },
      { word: 'Detector', korean: '탐지기', emoji: '🔍' },
      { word: 'Defense', korean: '방어', emoji: '🛡️' },
      { word: 'Destroy', korean: '파괴', emoji: '💥' },
      { word: 'Dive', korean: '잠수', emoji: '🌊' },
    ],
  },
  {
    uppercase: 'E',
    lowercase: 'e',
    name: '이',
    words: [
      { word: 'Engineering Bay', korean: '공학연구소', emoji: '🔬' },
      { word: 'Extractor', korean: '추출기', emoji: '⛏️' },
      { word: 'Ensnare', korean: '덫', emoji: '🕸️' },
      { word: 'Egg', korean: '알', emoji: '🥚' },
      { word: 'Energy', korean: '에너지', emoji: '⚡' },
      { word: 'Evolve', korean: '진화', emoji: '🔄' },
      { word: 'Emp', korean: 'EMP', emoji: '💥' },
      { word: 'Enhance', korean: '강화', emoji: '⬆️' },
      { word: 'Explode', korean: '폭발', emoji: '💣' },
      { word: 'Escape', korean: '도망', emoji: '🏃' },
    ],
  },
  {
    uppercase: 'F',
    lowercase: 'f',
    name: '에프',
    words: [
      { word: 'Factory', korean: '공장', emoji: '🏭' },
      { word: 'Firebat', korean: '화염방사병', emoji: '🔥' },
      { word: 'Fleet Beacon', korean: '함대 신호기', emoji: '📡' },
      { word: 'Forge', korean: '대장간', emoji: '⚒️' },
      { word: 'Fusion Core', korean: '융합핵', emoji: '⚛️' },
      { word: 'Fight', korean: '전투', emoji: '⚔️' },
      { word: 'Fly', korean: '비행', emoji: '✈️' },
      { word: 'Fire', korean: '불', emoji: '🔥' },
      { word: 'Force', korean: '힘', emoji: '💪' },
      { word: 'Field', korean: '필드', emoji: '🌾' },
    ],
  },
  {
    uppercase: 'G',
    lowercase: 'g',
    name: '지',
    words: [
      { word: 'Gateway', korean: '관문', emoji: '🚪' },
      { word: 'Ghost', korean: '고스트', emoji: '👻' },
      { word: 'Goliath', korean: '골리앗', emoji: '🤖' },
      { word: 'Guardian', korean: '가디언', emoji: '🦅' },
      { word: 'Greater Spire', korean: '대군락', emoji: '🏛️' },
      { word: 'Ground', korean: '지상', emoji: '🌍' },
      { word: 'Gather', korean: '수집', emoji: '📦' },
      { word: 'Gun', korean: '총', emoji: '🔫' },
      { word: 'Guard', korean: '방어', emoji: '🛡️' },
      { word: 'Group', korean: '그룹', emoji: '👥' },
    ],
  },
  {
    uppercase: 'H',
    lowercase: 'h',
    name: '에이치',
    words: [
      { word: 'Hatchery', korean: '부화장', emoji: '🥚' },
      { word: 'High Templar', korean: '하이 템플러', emoji: '🧙' },
      { word: 'Hydralisk', korean: '히드라리스크', emoji: '🐉' },
      { word: 'Hive', korean: '둥지', emoji: '🏛️' },
      { word: 'Hyperion', korean: '하이페리온', emoji: '🚢' },
      { word: 'Heal', korean: '치유', emoji: '💚' },
      { word: 'Hold', korean: '유지', emoji: '✋' },
      { word: 'Hide', korean: '숨기', emoji: '🙈' },
      { word: 'Hunt', korean: '사냥', emoji: '🎯' },
      { word: 'Hurt', korean: '상처', emoji: '🩹' },
    ],
  },
  {
    uppercase: 'I',
    lowercase: 'i',
    name: '아이',
    words: [
      { word: 'Interceptor', korean: '요격기', emoji: '🛸' },
      { word: 'Infested Terran', korean: '감염된 테란', emoji: '🦠' },
      { word: 'Infestation Pit', korean: '감염구덩이', emoji: '🕳️' },
      { word: 'Ion Cannon', korean: '이온포', emoji: '⚡' },
      { word: 'Immortal', korean: '불멸자', emoji: '🛡️' },
      { word: 'Infest', korean: '감염', emoji: '🦠' },
      { word: 'Invade', korean: '침략', emoji: '⚔️' },
      { word: 'Invisible', korean: '투명', emoji: '👻' },
      { word: 'Interface', korean: '인터페이스', emoji: '🖥️' },
      { word: 'Impact', korean: '충격', emoji: '💥' },
    ],
  },
  {
    uppercase: 'J',
    lowercase: 'j',
    name: '제이',
    words: [
      { word: 'Jump', korean: '점프', emoji: '🚀' },
      { word: 'Join', korean: '참가', emoji: '🤝' },
      { word: 'Judge', korean: '판단', emoji: '⚖️' },
      { word: 'Jet', korean: '제트', emoji: '✈️' },
      { word: 'Jam', korean: '교란', emoji: '📡' },
      { word: 'Joint', korean: '연합', emoji: '🔗' },
      { word: 'Journey', korean: '여행', emoji: '🗺️' },
      { word: 'Junction', korean: '연결점', emoji: '🔌' },
      { word: 'Javelin', korean: '재블린', emoji: '🏹' },
      { word: 'Justice', korean: '정의', emoji: '⚖️' },
    ],
  },
  {
    uppercase: 'K',
    lowercase: 'k',
    name: '케이',
    words: [
      { word: 'Kerrigan', korean: '케리건', emoji: '👸' },
      { word: 'Key', korean: '열쇠', emoji: '🔑' },
      { word: 'Kill', korean: '처치', emoji: '⚔️' },
      { word: 'Kinetic', korean: '운동', emoji: '⚡' },
      { word: 'Knight', korean: '기사', emoji: '🛡️' },
      { word: 'Knock', korean: '타격', emoji: '👊' },
      { word: 'Knowledge', korean: '지식', emoji: '📚' },
      { word: 'Korhal', korean: '코랄', emoji: '🌍' },
      { word: 'Keep', korean: '유지', emoji: '🔒' },
      { word: 'Kick', korean: '차기', emoji: '🦵' },
    ],
  },
  {
    uppercase: 'L',
    lowercase: 'l',
    name: '엘',
    words: [
      { word: 'Larva', korean: '라바', emoji: '🐛' },
      { word: 'Lair', korean: '소굴', emoji: '🕳️' },
      { word: 'Lurker', korean: '땅거미', emoji: '🕷️' },
      { word: 'Liberator', korean: '해방자', emoji: '🚁' },
      { word: 'Laser', korean: '레이저', emoji: '🔴' },
      { word: 'Launch', korean: '발사', emoji: '🚀' },
      { word: 'Lockdown', korean: '잠금', emoji: '🔒' },
      { word: 'Light', korean: '빛', emoji: '💡' },
      { word: 'Life', korean: '생명', emoji: '❤️' },
      { word: 'Lift', korean: '수송', emoji: '🚁' },
    ],
  },
  {
    uppercase: 'M',
    lowercase: 'm',
    name: '엠',
    words: [
      { word: 'Marine', korean: '해병', emoji: '👨‍✈️' },
      { word: 'Mutalisk', korean: '뮤탈리스크', emoji: '🦅' },
      { word: 'Medic', korean: '의무관', emoji: '⚕️' },
      { word: 'Missile', korean: '미사일', emoji: '🚀' },
      { word: 'Mothership', korean: '모선', emoji: '🚢' },
      { word: 'Mine', korean: '지뢰', emoji: '💣' },
      { word: 'Move', korean: '이동', emoji: '🚶' },
      { word: 'Mass', korean: '집단', emoji: '👥' },
      { word: 'Machine', korean: '기계', emoji: '⚙️' },
      { word: 'Mission', korean: '임무', emoji: '🎯' },
    ],
  },
  {
    uppercase: 'N',
    lowercase: 'n',
    name: '엔',
    words: [
      { word: 'Nexus', korean: '넥서스', emoji: '🏛️' },
      { word: 'Nuclear', korean: '핵', emoji: '☢️' },
      { word: 'Nydus', korean: '나이더스', emoji: '🕳️' },
      { word: 'Nuke', korean: '핵폭탄', emoji: '💣' },
      { word: 'Neural', korean: '신경', emoji: '🧠' },
      { word: 'Network', korean: '네트워크', emoji: '🌐' },
      { word: 'Nest', korean: '둥지', emoji: '🪺' },
      { word: 'Night', korean: '밤', emoji: '🌙' },
      { word: 'Naval', korean: '해군', emoji: '🚢' },
      { word: 'Node', korean: '노드', emoji: '🔗' },
    ],
  },
  {
    uppercase: 'O',
    lowercase: 'o',
    name: '오',
    words: [
      { word: 'Observer', korean: '옵저버', emoji: '👁️' },
      { word: 'Overlord', korean: '오버로드', emoji: '🛸' },
      { word: 'Oracle', korean: '오라클', emoji: '🔮' },
      { word: 'Overseer', korean: '감시자', emoji: '👁️' },
      { word: 'Orbital', korean: '궤도', emoji: '🛰️' },
      { word: 'Overcharge', korean: '과충전', emoji: '⚡' },
      { word: 'Offense', korean: '공격', emoji: '⚔️' },
      { word: 'Order', korean: '명령', emoji: '📜' },
      { word: 'Objective', korean: '목표', emoji: '🎯' },
      { word: 'Outpost', korean: '전초기지', emoji: '🏰' },
    ],
  },
  {
    uppercase: 'P',
    lowercase: 'p',
    name: '피',
    words: [
      { word: 'Probe', korean: '탐사정', emoji: '🔧' },
      { word: 'Phoenix', korean: '피닉스', emoji: '🔥' },
      { word: 'Psi Storm', korean: '사이오닉 폭풍', emoji: '⚡' },
      { word: 'Pylon', korean: '파일런', emoji: '💎' },
      { word: 'Prism', korean: '프리즘', emoji: '🔮' },
      { word: 'Protoss', korean: '프로토스', emoji: '👽' },
      { word: 'Power', korean: '파워', emoji: '⚡' },
      { word: 'Plasma', korean: '플라즈마', emoji: '🔵' },
      { word: 'Pulse', korean: '펄스', emoji: '💓' },
      { word: 'Pierce', korean: '관통', emoji: '➡️' },
    ],
  },
  {
    uppercase: 'Q',
    lowercase: 'q',
    name: '큐',
    words: [
      { word: 'Queen', korean: '퀸', emoji: '👑' },
      { word: 'Quick', korean: '빠른', emoji: '⚡' },
      { word: 'Quake', korean: '지진', emoji: '🌍' },
      { word: 'Quality', korean: '품질', emoji: '⭐' },
      { word: 'Quarry', korean: '채석장', emoji: '⛏️' },
      { word: 'Quest', korean: '퀘스트', emoji: '🗺️' },
      { word: 'Queue', korean: '대기열', emoji: '📋' },
      { word: 'Quiet', korean: '조용한', emoji: '🤫' },
      { word: 'Quill', korean: '깃털', emoji: '🪶' },
      { word: 'Quartz', korean: '수정', emoji: '💎' },
    ],
  },
  {
    uppercase: 'R',
    lowercase: 'r',
    name: '알',
    words: [
      { word: 'Reaver', korean: '리버', emoji: '🤖' },
      { word: 'Raynor', korean: '레이너', emoji: '👨‍✈️' },
      { word: 'Raven', korean: '레이븐', emoji: '🦅' },
      { word: 'Roach', korean: '바퀴', emoji: '🪲' },
      { word: 'Reaper', korean: '사신', emoji: '💀' },
      { word: 'Robotics', korean: '로보틱스', emoji: '🤖' },
      { word: 'Refinery', korean: '정제소', emoji: '⛽' },
      { word: 'Rally', korean: '집결', emoji: '📍' },
      { word: 'Range', korean: '사거리', emoji: '📏' },
      { word: 'Rush', korean: '러시', emoji: '⚡' },
    ],
  },
  {
    uppercase: 'S',
    lowercase: 's',
    name: '에스',
    words: [
      { word: 'SCV', korean: '건설로봇', emoji: '🔧' },
      { word: 'Siege Tank', korean: '시즈 탱크', emoji: '🚗' },
      { word: 'Spawning Pool', korean: '번식지', emoji: '🕳️' },
      { word: 'Stargate', korean: '성문', emoji: '🚪' },
      { word: 'Starport', korean: '우주공항', emoji: '🚀' },
      { word: 'Scout', korean: '정찰기', emoji: '🛩️' },
      { word: 'Scourge', korean: '스커지', emoji: '💥' },
      { word: 'Science Vessel', korean: '사이언스 베슬', emoji: '🔬' },
      { word: 'Shuttle', korean: '셔틀', emoji: '🚁' },
      { word: 'Spire', korean: '군락', emoji: '🏛️' },
    ],
  },
  {
    uppercase: 'T',
    lowercase: 't',
    name: '티',
    words: [
      { word: 'Terran', korean: '테란', emoji: '👨‍✈️' },
      { word: 'Templar', korean: '템플러', emoji: '🧙' },
      { word: 'Thor', korean: '토르', emoji: '🤖' },
      { word: 'Twilight', korean: '황혼', emoji: '🌆' },
      { word: 'Tower', korean: '타워', emoji: '🗼' },
      { word: 'Transport', korean: '수송', emoji: '🚁' },
      { word: 'Tank', korean: '탱크', emoji: '🚗' },
      { word: 'Tech', korean: '기술', emoji: '⚙️' },
      { word: 'Target', korean: '목표', emoji: '🎯' },
      { word: 'Turret', korean: '포탑', emoji: '🔫' },
    ],
  },
  {
    uppercase: 'U',
    lowercase: 'u',
    name: '유',
    words: [
      { word: 'Ultralisk', korean: '울트라리스크', emoji: '🦏' },
      { word: 'Uplink', korean: '연결', emoji: '📡' },
      { word: 'Upgrade', korean: '업그레이드', emoji: '⬆️' },
      { word: 'Unit', korean: '유닛', emoji: '👤' },
      { word: 'Unload', korean: '하역', emoji: '📦' },
      { word: 'Unlock', korean: '잠금해제', emoji: '🔓' },
      { word: 'Union', korean: '연합', emoji: '🤝' },
      { word: 'Uranium', korean: '우라늄', emoji: '☢️' },
      { word: 'Ultimate', korean: '궁극', emoji: '🌟' },
      { word: 'Underground', korean: '지하', emoji: '🕳️' },
    ],
  },
  {
    uppercase: 'V',
    lowercase: 'v',
    name: '브이',
    words: [
      { word: 'Vulture', korean: '벌처', emoji: '🏍️' },
      { word: 'Void Ray', korean: '공허 포격기', emoji: '⚡' },
      { word: 'Vespene', korean: '베스핀 가스', emoji: '💨' },
      { word: 'Viking', korean: '바이킹', emoji: '✈️' },
      { word: 'Valkyrie', korean: '발키리', emoji: '🛩️' },
      { word: 'Vision', korean: '시야', emoji: '👁️' },
      { word: 'Vital', korean: '중요한', emoji: '❤️' },
      { word: 'Victory', korean: '승리', emoji: '🏆' },
      { word: 'Volcano', korean: '화산', emoji: '🌋' },
      { word: 'Vortex', korean: '소용돌이', emoji: '🌀' },
    ],
  },
  {
    uppercase: 'W',
    lowercase: 'w',
    name: '더블유',
    words: [
      { word: 'Wraith', korean: '레이스', emoji: '🛩️' },
      { word: 'Warp', korean: '워프', emoji: '✨' },
      { word: 'Warrior', korean: '전사', emoji: '⚔️' },
      { word: 'Worker', korean: '일꾼', emoji: '👷' },
      { word: 'Weapon', korean: '무기', emoji: '🔫' },
      { word: 'Win', korean: '승리', emoji: '🏆' },
      { word: 'Wave', korean: '파도', emoji: '🌊' },
      { word: 'Worm', korean: '벌레', emoji: '🪱' },
      { word: 'Wound', korean: '상처', emoji: '🩹' },
      { word: 'Watch', korean: '감시', emoji: '👁️' },
    ],
  },
  {
    uppercase: 'X',
    lowercase: 'x',
    name: '엑스',
    words: [
      { word: 'Xel\'Naga', korean: '젤나가', emoji: '👽' },
      { word: 'Xeno', korean: '외계인', emoji: '👽' },
      { word: 'X-Ray', korean: '엑스레이', emoji: '🔍' },
      { word: 'Xenon', korean: '제논', emoji: '💡' },
      { word: 'Xylem', korean: '물관', emoji: '🌿' },
      { word: 'Xylophone', korean: '실로폰', emoji: '🎹' },
      { word: 'X-axis', korean: 'X축', emoji: '📐' },
      { word: 'Xenomorph', korean: '제노모프', emoji: '👾' },
      { word: 'X-factor', korean: 'X요소', emoji: '❓' },
      { word: 'Xenobiology', korean: '외계생물학', emoji: '🧬' },
    ],
  },
  {
    uppercase: 'Y',
    lowercase: 'y',
    name: '와이',
    words: [
      { word: 'Yamato', korean: '야마토 포', emoji: '💥' },
      { word: 'Yield', korean: '수확', emoji: '📦' },
      { word: 'Young', korean: '젊은', emoji: '👶' },
      { word: 'Year', korean: '년', emoji: '📅' },
      { word: 'Yellow', korean: '노란색', emoji: '🟡' },
      { word: 'Yell', korean: '외치다', emoji: '📢' },
      { word: 'Yard', korean: '마당', emoji: '🏡' },
      { word: 'Yawn', korean: '하품', emoji: '😴' },
      { word: 'Yet', korean: '아직', emoji: '⏳' },
      { word: 'Your', korean: '당신의', emoji: '👤' },
    ],
  },
  {
    uppercase: 'Z',
    lowercase: 'z',
    name: '제드',
    words: [
      { word: 'Zerg', korean: '저그', emoji: '🐛' },
      { word: 'Zealot', korean: '질럿', emoji: '⚔️' },
      { word: 'Zergling', korean: '저글링', emoji: '🦗' },
      { word: 'Zero', korean: '영', emoji: '0️⃣' },
      { word: 'Zone', korean: '구역', emoji: '📍' },
      { word: 'Zoom', korean: '확대', emoji: '🔍' },
      { word: 'Zap', korean: '번개', emoji: '⚡' },
      { word: 'Zenith', korean: '정점', emoji: '🔝' },
      { word: 'Zephyr', korean: '미풍', emoji: '💨' },
      { word: 'Zombie', korean: '좀비', emoji: '🧟' },
    ],
  },
];
